#pragma once

#include <libdeflate.h>
#include <algorithm>
#include <array>
#include <bit>
#include <condition_variable>
#include <cstdint>
#include <filesystem>
#include <format>
#include <fstream>
#include <memory>
#include <mutex>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <thread>
#include <vector>

#include <cuddl/error.hpp>

#if defined(__aarch64__) || defined(_M_ARM64)
    #include <arm_neon.h>
#endif
#if defined(__ARM_FEATURE_SVE)
    #include <arm_sve.h>
#elif defined(__x86_64__) || defined(_M_X64)
    #include <immintrin.h>
#endif

#if defined(__linux__)
    #include <fcntl.h>
    #include <sys/mman.h>
    #include <sys/stat.h>
    #include <unistd.h>
#endif

namespace cuddl::detail {

/// @brief A contiguous run of sequence bases (record headers and line breaks excluded).
struct fastx_sequence_extent {
    char const* begin;
    char const* end;
};

/// @brief True for bytes that FASTA sequence consumers conventionally skip between bases.
[[nodiscard]] inline constexpr bool fastx_is_sequence_whitespace(char ch) noexcept {
    return ch == '\n' || ch == '\r' || ch == ' ' || ch == '\t';
}

// SIMD line scanners: https://github.com/tdortman/cuSBF
// Source revision: ec678b0750b0067d4fc66e066c8cd7a67cc5e792
/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
[[nodiscard]] inline size_t fastx_line_end_scalar(std::string_view data, size_t position) {
    while (position < data.size() && data[position] != '\n' && data[position] != '\r') {
        ++position;
    }
    return position;
}

#if (defined(__GNUC__) || defined(__clang__)) && defined(__x86_64__) && !defined(__CUDACC__)
[[gnu::target("avx2")]] [[nodiscard]] inline size_t
fastx_line_end_avx2(std::string_view data, size_t position) {
    const __m256i newline = _mm256_set1_epi8('\n');
    const __m256i carriage_return = _mm256_set1_epi8('\r');
    while (data.size() - position >= 32) {
        const __m256i bytes =
            _mm256_loadu_si256(reinterpret_cast<const __m256i*>(data.data() + position));
        const auto mask = static_cast<uint32_t>(_mm256_movemask_epi8(_mm256_or_si256(
            _mm256_cmpeq_epi8(bytes, newline), _mm256_cmpeq_epi8(bytes, carriage_return)
        )));
        if (mask != 0) {
            return position + static_cast<size_t>(__builtin_ctz(mask));
        }
        position += 32;
    }
    return fastx_line_end_scalar(data, position);
}
#endif

#if defined(__ARM_FEATURE_SVE)
[[nodiscard]] inline size_t fastx_line_end_sve(std::string_view data, size_t position) {
    while (position < data.size()) {
        const svbool_t active = svwhilelt_b8(position, data.size());
        const svuint8_t bytes =
            svld1_u8(active, reinterpret_cast<const uint8_t*>(data.data() + position));
        const svbool_t matches =
            svorr_b_z(active, svcmpeq_n_u8(active, bytes, '\n'), svcmpeq_n_u8(active, bytes, '\r'));
        if (svptest_any(active, matches)) {
            return position + svcntp_b8(active, svbrkb_z(active, matches));
        }
        position += svcntb();
    }
    return position;
}
#endif

#if defined(__aarch64__) || defined(_M_ARM64)
[[nodiscard]] inline size_t fastx_line_end_neon(std::string_view data, size_t position) {
    const uint8x16_t newline = vdupq_n_u8('\n');
    const uint8x16_t carriage_return = vdupq_n_u8('\r');
    while (data.size() - position >= 16) {
        const uint8x16_t bytes = vld1q_u8(reinterpret_cast<const uint8_t*>(data.data() + position));
        const uint8x16_t matches =
            vorrq_u8(vceqq_u8(bytes, newline), vceqq_u8(bytes, carriage_return));
        const uint64x2_t words = vreinterpretq_u64_u8(matches);
        const uint64_t low = vgetq_lane_u64(words, 0);
        if (low != 0) {
            return position + (std::countr_zero(low) >> 3);
        }
        const uint64_t high = vgetq_lane_u64(words, 1);
        if (high != 0) {
            return position + 8 + (std::countr_zero(high) >> 3);
        }
        position += 16;
    }
    return fastx_line_end_scalar(data, position);
}
#endif

using fastx_line_end_fn = decltype(&fastx_line_end_scalar);

[[nodiscard]] inline fastx_line_end_fn resolve_fastx_line_end() {
#if defined(__ARM_FEATURE_SVE)
    return fastx_line_end_sve;
#elif defined(__aarch64__) || defined(_M_ARM64)
    return fastx_line_end_neon;
#elif (defined(__GNUC__) || defined(__clang__)) && defined(__x86_64__) && !defined(__CUDACC__)
    return __builtin_cpu_supports("avx2") ? fastx_line_end_avx2 : fastx_line_end_scalar;
#else
    return fastx_line_end_scalar;
#endif
}

static const fastx_line_end_fn line_end = resolve_fastx_line_end();

[[nodiscard]] inline size_t fastx_line_end(std::string_view data, size_t position) {
    return line_end(data, position);
}

/**
 * @brief Collects the sequence extents of every FASTA record in @p data.
 *
 * Each extent spans from the byte after a `>` header line to the byte before the next `>`
 * header line (or the end of the buffer), header bytes excluded. Search directly for header
 * markers with string_view::find; only header lines need a line-end scan. Bytes outside extents are
 * not part of any extent.
 */
[[nodiscard]] inline std::vector<fastx_sequence_extent> fastx_fasta_extents(std::string_view data) {
    std::vector<fastx_sequence_extent> extents;
    size_t sequence = std::string_view::npos;
    size_t header = data.find('>');
    while (header != std::string_view::npos) {
        if (header != 0 && data[header - 1] != '\n' && data[header - 1] != '\r') {
            header = data.find('>', header + 1);
            continue;
        }
        if (sequence != std::string_view::npos && header > sequence) {
            extents.push_back({data.data() + sequence, data.data() + header});
        }
        auto const end = fastx_line_end(data, header);
        sequence = end < data.size() ? end + 1 : data.size();
        header = data.find('>', sequence);
    }
    if (sequence != std::string_view::npos && sequence < data.size()) {
        extents.push_back({data.data() + sequence, data.data() + data.size()});
    }
    return extents;
}

// Collects every '>' offset in data[begin, end). Phase one of the parallel FASTA scan:
// pure search, no header interpretation.
inline void gather_header_candidates(
    std::string_view data,
    size_t begin,
    size_t end,
    std::vector<size_t>& out
) {
    auto const segment = data.substr(begin, end - begin);
    size_t pos = 0;
    while (true) {
        auto const found = segment.find('>', pos);
        if (found == std::string_view::npos) return;
        out.push_back(begin + found);
        pos = found + 1;
    }
}

// Serial header walk over ascending '>' candidates. Produces exactly
// fastx_fasta_extents(data): candidates before the cursor are bytes a
// serial search jumps over with its line-end skip, and the predecessor rule is local.
inline std::vector<fastx_sequence_extent>
walk_header_candidates(std::string_view data, std::vector<size_t> const& candidates) {
    std::vector<fastx_sequence_extent> extents;
    size_t sequence = std::string_view::npos;
    size_t cursor = 0;
    for (auto const header : candidates) {
        if (header < cursor) continue;
        if (header != 0 && data[header - 1] != '\n' && data[header - 1] != '\r') {
            cursor = header + 1;
            continue;
        }
        if (sequence != std::string_view::npos && header > sequence) {
            extents.push_back({data.data() + sequence, data.data() + header});
        }
        auto const end = fastx_line_end(data, header);
        sequence = end < data.size() ? end + 1 : data.size();
        cursor = sequence;
    }
    if (sequence != std::string_view::npos && sequence < data.size()) {
        extents.push_back({data.data() + sequence, data.data() + data.size()});
    }
    return extents;
}

// Parallel equivalent of fastx_fasta_extents for large inputs. Shards the
// '>' search (the full-buffer memchr pass) across threads, then walks the ordered
// candidates once. Small inputs use the serial scan directly.
inline std::vector<fastx_sequence_extent> parallel_fastx_fasta_extents(std::string_view data) {
    auto const hardware = std::max(1U, std::thread::hardware_concurrency());
    auto const shards =
        std::min<size_t>(std::min<unsigned>(hardware, 8U), data.size() / (size_t{64} << 20) + 1);
    if (shards <= 1) return fastx_fasta_extents(data);
    std::vector<std::vector<size_t>> gathered(shards);
    std::vector<std::thread> workers;
    workers.reserve(shards - 1);
    auto const span = (data.size() + shards - 1) / shards;
    for (size_t shard = 1; shard < shards; ++shard) {
        workers.emplace_back([&, shard] {
            auto const begin = std::min(shard * span, data.size());
            gather_header_candidates(
                data, begin, std::min(begin + span, data.size()), gathered[shard]
            );
        });
    }
    gather_header_candidates(data, 0, std::min(span, data.size()), gathered[0]);
    for (auto& worker : workers) worker.join();
    std::vector<size_t> candidates;
    for (auto const& shard : gathered)
        candidates.insert(candidates.end(), shard.begin(), shard.end());
    return walk_header_candidates(data, candidates);
}

/// @brief Read-only contiguous file payload for in-memory FASTX parsing.
///
/// Plain files stay memory-mapped on Linux, so FASTA extents reference the mapping with no
/// copy. Other platforms read the file into memory.
class fastx_mapped_file {
   public:
    fastx_mapped_file() = default;
    fastx_mapped_file(fastx_mapped_file const&) = delete;
    fastx_mapped_file& operator=(fastx_mapped_file const&) = delete;
    fastx_mapped_file(fastx_mapped_file&& other) noexcept {
        *this = std::move(other);
    }

    fastx_mapped_file& operator=(fastx_mapped_file&& other) noexcept {
        if (this != &other) {
            release();
            owned_storage_ = std::move(other.owned_storage_);
            data_ = other.data_;
            size_ = other.size_;
            other.data_ = nullptr;
            other.size_ = 0;
#if defined(__linux__)
            mapped_ = other.mapped_;
            mapped_size_ = other.mapped_size_;
            other.mapped_ = nullptr;
            other.mapped_size_ = 0;
#endif
        }
        return *this;
    }

    ~fastx_mapped_file() {
        release();
    }

    /**
     * @brief Loads a file via mmap (Linux) or read into memory.
     *
     * Empty files succeed with empty data. Any failure carries the reason; the FASTX loader
     * maps it to its stable "cannot open" error.
     */
    [[nodiscard]] static Result<std::unique_ptr<fastx_mapped_file>> load(std::string const& path) {
        auto buffer = std::make_unique<fastx_mapped_file>();
        auto loaded = buffer->load_from_path(path);
        if (!loaded) return Err(loaded.error());
        return buffer;
    }

    /// @brief Contiguous read-only file bytes.
    [[nodiscard]] std::string_view data() const noexcept {
        return std::string_view{data_, size_};
    }

    /// @brief True when the file is empty or load produced no bytes.
    [[nodiscard]] bool empty() const noexcept {
        return size_ == 0;
    }

   private:
    std::vector<char> owned_storage_;
    char const* data_{nullptr};
    size_t size_{0};

#if defined(__linux__)
    void* mapped_{nullptr};
    size_t mapped_size_{0};
#endif

    void release() {
#if defined(__linux__)
        if (mapped_ != nullptr) {
            munmap(mapped_, mapped_size_);
            mapped_ = nullptr;
            mapped_size_ = 0;
        }
#endif
        owned_storage_.clear();
        data_ = nullptr;
        size_ = 0;
    }

    [[nodiscard]] Result<void> load_from_path(std::string const& path) {
#if defined(__linux__)
        int const fd = ::open(path.c_str(), O_RDONLY);
        if (fd == -1) {
            return Err(Error::invalid_argument("Failed to open FASTA/FASTQ file: " + path));
        }

        struct stat file_status{};
        if (::fstat(fd, &file_status) != 0 || file_status.st_size < 0) {
            ::close(fd);
            return Err(Error::invalid_argument("Failed to stat FASTA/FASTQ file: " + path));
        }

        if (file_status.st_size == 0) {
            ::close(fd);
            return Ok();
        }

        mapped_size_ = static_cast<size_t>(file_status.st_size);
        mapped_ = ::mmap(nullptr, mapped_size_, PROT_READ, MAP_PRIVATE, fd, 0);
        ::close(fd);
        if (mapped_ == MAP_FAILED) {
            mapped_ = nullptr;
            mapped_size_ = 0;
            return Err(Error::invalid_argument("Failed to mmap FASTA/FASTQ file: " + path));
        }

        data_ = static_cast<char const*>(mapped_);
        size_ = mapped_size_;
        return Ok();
#else
        std::ifstream input(path, std::ios::binary);
        if (!input.is_open()) {
            return Err(Error::invalid_argument("Failed to open FASTA/FASTQ file: " + path));
        }
        input.seekg(0, std::ios::end);
        auto const file_size = input.tellg();
        if (file_size < 0) {
            return Err(Error::invalid_argument("Failed to size FASTA/FASTQ file: " + path));
        }
        owned_storage_.resize(static_cast<size_t>(file_size));
        input.seekg(0, std::ios::beg);
        if (!owned_storage_.empty()) {
            input.read(owned_storage_.data(), static_cast<std::streamsize>(owned_storage_.size()));
            if (!input) {
                return Err(Error::invalid_argument("Failed to read FASTA/FASTQ file: " + path));
            }
        }
        data_ = owned_storage_.data();
        size_ = owned_storage_.size();
        return Ok();
#endif
    }
};

/// @brief Detected record format for a FASTX buffer.
enum class fastx_format : uint8_t {
    /// Format not yet determined from the first header.
    unknown,
    /// FASTA (`>` headers).
    fasta,
    /// FASTQ (`@` headers).
    fastq,
};

/**
 * @brief FASTQ parser over a contiguous in-memory buffer.
 *
 * Accumulates multiline sequence lines and validates multiline qualities against the
 * sequence length, exactly as the FASTA path's record scan excludes header bytes: only
 * sequence bytes reach the caller. The first header fixes the format; a later header of
 * the other kind is a mixed-format error.
 */
class fastx_fastq_reader {
   public:
    /**
     * @brief Constructs a reader over a contiguous in-memory FASTQ buffer.
     *
     * @param data         Entire file or decompressed payload.
     * @param source_name  Label used in parse error messages.
     */
    explicit fastx_fastq_reader(std::string_view data, std::string source_name = "<buffer>")
        : data_(data), source_name_(std::move(source_name)) {}

    /**
     * @brief Appends the next record's sequence bytes to @p sequence.
     *
     * @return @c false at end-of-buffer, @c true when a record was read, or an error.
     */
    [[nodiscard]] Result<bool> append_next_record(std::string& sequence) {
        auto header = CUDDL_TRY(read_header_line());
        if (header.empty()) {
            return false;
        }

        char const tag = header.front();
        if (format_ == fastx_format::unknown) {
            if (tag == '>') {
                format_ = fastx_format::fasta;
            } else if (tag == '@') {
                format_ = fastx_format::fastq;
            } else {
                return Err(parse_error("expected FASTA or FASTQ header"));
            }
        }

        char const expected = format_ == fastx_format::fasta ? '>' : '@';
        if (tag != expected) {
            return Err(parse_error("mixed FASTA and FASTQ records are not supported"));
        }
        if (format_ != fastx_format::fastq) {
            return Err(parse_error("mixed FASTA and FASTQ records are not supported"));
        }
        auto const base = sequence.size();
        CUDDL_TRY(read_fastq_sequence(sequence, base));
        return true;
    }

   private:
    std::string_view data_;
    std::string source_name_;
    size_t position_{0};
    fastx_format format_{fastx_format::unknown};
    uint64_t line_number_{};

    [[nodiscard]] Error parse_error(std::string_view message) const {
        return Error::invalid_argument(
            std::format("{}:{}: {}", source_name_, line_number_, message)
        );
    }

    [[nodiscard]] std::string_view read_line() {
        if (position_ >= data_.size()) {
            return {};
        }

        size_t const end = fastx_line_end(data_, position_);

        std::string_view const line = data_.substr(position_, end - position_);
        position_ = end;
        if (position_ < data_.size() && data_[position_] == '\r') {
            ++position_;
        }
        if (position_ < data_.size() && data_[position_] == '\n') {
            ++position_;
        }
        ++line_number_;
        return line;
    }

    [[nodiscard]] Result<std::string_view> read_header_line() {
        while (position_ < data_.size()) {
            std::string_view const line = read_line();
            if (!line.empty()) {
                return line;
            }
        }
        return std::string_view{};
    }

    [[nodiscard]] Result<void> read_fastq_sequence(std::string& sequence, size_t base) {
        while (position_ < data_.size()) {
            std::string_view const line = read_line();
            if (!line.empty() && line.front() == '+') {
                return read_fastq_qualities(sequence.size() - base);
            }
            sequence.append(line.data(), line.size());
        }
        return Err(parse_error("unterminated FASTQ record: missing '+' separator"));
    }

    [[nodiscard]] Result<void> read_fastq_qualities(uint64_t expected_length) {
        uint64_t quality_length = 0;
        while (quality_length < expected_length && position_ < data_.size()) {
            std::string_view const line = read_line();
            quality_length += line.size();
            if (quality_length > expected_length) {
                return Err(parse_error("FASTQ quality length exceeds sequence length"));
            }
        }
        if (quality_length != expected_length) {
            return Err(parse_error("FASTQ quality length does not match sequence length"));
        }
        return Ok();
    }
};

// Heap ownership keeps extent addresses stable, including short decompressed strings.
struct fastx_sequence_file {
    std::unique_ptr<fastx_mapped_file> file;
    std::string decompressed;
    std::string sequence;
    std::vector<fastx_sequence_extent> extents;
    // Set when the caller supplied memory for the decompressed bytes, which then live outside
    // this object and stay valid as long as the caller keeps them. `decompressed` stays empty.
    char* decompressed_target = nullptr;
    size_t decompressed_size = 0;
    std::shared_ptr<void> storage_owner;
};

/// @brief Host-visible buffer a caller offers for decompressed bytes.
///
/// GPU callers supply page-locked memory so the transfer engine can read the sequence
/// in place, which removes the staging copy that a heap buffer would need. `owner` keeps the
/// storage alive for as long as the parsed file holds it.
struct decompression_target {
    char* data = nullptr;
    size_t capacity = 0;
    std::shared_ptr<void> owner;
};

/// @brief Supplies page-locked storage for one file, or a null target when none is available.
///
/// Reusing buffers is the caller's problem, so it decides how much page-locked memory to
/// commit. A null target simply leaves the loader on its own growing buffer.
struct decompression_source {
    decompression_target (*acquire)(void* context, size_t bytes) = nullptr;
    void* context = nullptr;

    [[nodiscard]] decompression_target request(size_t bytes) const {
        return acquire != nullptr ? acquire(context, bytes) : decompression_target{};
    }
};

/// @brief libdeflate handle, one per thread because the object is single-threaded.
struct shared_gzip_decompressor {
    libdeflate_decompressor* handle{libdeflate_alloc_decompressor()};
    shared_gzip_decompressor() = default;
    shared_gzip_decompressor(shared_gzip_decompressor const&) = delete;
    shared_gzip_decompressor& operator=(shared_gzip_decompressor const&) = delete;
    ~shared_gzip_decompressor() {
        libdeflate_free_decompressor(handle);
    }
};

/// @brief Decompresses gzip members from a mapped buffer into @p output, appending.
///
/// Members are decompressed one at a time so concatenated streams (BGZF among them) work.
/// libdeflate verifies each member's CRC32 and length trailer, so corrupt and truncated
/// input both fail here instead of yielding partial sequence. `output` grows as needed, so a
/// caller that pre-sized storage can only ever save reallocations, never lose data.
[[nodiscard]] inline Result<void>
gunzip_members_into(std::string_view input, std::string& output, std::string const& path) {
    static thread_local shared_gzip_decompressor shared;
    if (shared.handle == nullptr) {
        return Err(Error::resource("cannot allocate gzip decompressor"));
    }
    // Genomes compress around 3x; guessing low costs a realloc per member, not correctness.
    if (output.empty()) output.resize(std::max<size_t>(input.size() * 4, 1U << 16));
    size_t consumed = 0;
    size_t produced = 0;
    while (consumed < input.size()) {
        size_t member_in = 0;
        size_t member_out = 0;
        auto const status = libdeflate_gzip_decompress_ex(
            shared.handle,
            input.data() + consumed,
            input.size() - consumed,
            output.data() + produced,
            output.size() - produced,
            &member_in,
            &member_out
        );
        if (status == LIBDEFLATE_INSUFFICIENT_SPACE) {
            output.resize(output.size() * 2 + 1);
            continue;
        }
        if (status != LIBDEFLATE_SUCCESS) {
            return Err(Error::invalid_argument("gzip FASTX error: invalid stream: " + path));
        }
        consumed += member_in;
        produced += member_out;
    }
    output.resize(produced);
    return Ok();
}

/// @brief Decompresses gzip members straight into a caller's buffer.
///
/// Returns `Error::resource` when @p target is too small, which callers treat as a request to
/// fall back to the growing-string path rather than a failure.
[[nodiscard]] inline Result<size_t> gunzip_members_direct(
    std::string_view input,
    decompression_target target,
    bool& insufficient,
    std::string const& path
) {
    insufficient = false;
    static thread_local shared_gzip_decompressor shared;
    if (shared.handle == nullptr) {
        return Err(Error::resource("cannot allocate gzip decompressor"));
    }
    size_t consumed = 0;
    size_t produced = 0;
    while (consumed < input.size()) {
        size_t member_in = 0;
        size_t member_out = 0;
        auto const status = libdeflate_gzip_decompress_ex(
            shared.handle,
            input.data() + consumed,
            input.size() - consumed,
            target.data + produced,
            target.capacity - produced,
            &member_in,
            &member_out
        );
        if (status == LIBDEFLATE_INSUFFICIENT_SPACE) {
            // A caller-supplied buffer cannot grow, so the loader falls back instead.
            insufficient = true;
            return Result<size_t>::ok(0);
        }
        if (status != LIBDEFLATE_SUCCESS) {
            return Err(Error::invalid_argument("gzip FASTX error: invalid stream: " + path));
        }
        consumed += member_in;
        produced += member_out;
    }
    return produced;
}

/// @brief Uncompressed size the gzip trailer advertises, or 0 when it cannot be read.
///
/// `ISIZE` holds one member's length modulo 2^32, so a concatenated stream is only sized
/// correctly by its last member. A short buffer is refused later, never silently truncated.
/// @brief Exact decompressed size of @p path, or 0 when it is not a readable gzip file.
///
/// A gzip member ends with a little-endian ISIZE, so this needs a 4-byte read instead of a full
/// decompression pass. A corpus of these bounds how much a staged arena can ever hold.
[[nodiscard]] inline uint64_t gzip_decompressed_size(std::string const& path) {
    auto file = std::fopen(path.c_str(), "rb");
    if (file == nullptr) return 0;
    uint64_t size = 0;
    if (std::fseek(file, -4, SEEK_END) == 0) {
        unsigned char trailer[4] = {};
        if (std::fread(trailer, 1, sizeof(trailer), file) == sizeof(trailer)) {
            size = static_cast<uint64_t>(trailer[0]) | (static_cast<uint64_t>(trailer[1]) << 8) |
                   (static_cast<uint64_t>(trailer[2]) << 16) |
                   (static_cast<uint64_t>(trailer[3]) << 24);
        }
    }
    std::fclose(file);
    return size;
}

[[nodiscard]] inline size_t gzip_size_hint(std::string_view input) {
    if (input.size() < 8) return 0;
    auto const byte = [&](size_t index) {
        return static_cast<uint32_t>(static_cast<unsigned char>(input[index]));
    };
    auto const tail = input.size() - 4;
    return byte(tail) | (byte(tail + 1) << 8) | (byte(tail + 2) << 16) | (byte(tail + 3) << 24);
}

/// @brief Compacts sequence whitespace in place, leaving every extent a run of bases.
///
/// Consumers stage extents verbatim and choose piece boundaries on any base, which needs
/// contiguous bases. Compacting here moves the work onto the loader thread: each file is
/// compacted while the other loaders are still decompressing, and a consumer that used to skip
/// whitespace byte by byte now walks a dense span.
inline void compact_fastx_sequence_extents(fastx_sequence_file& result) {
    if (result.extents.empty()) return;
    // Extents point into whichever buffer holds the bytes: a page-locked target, the heap copy of
    // a compressed file, or the FASTQ sequence buffer. Those are writable; a memory-mapped plain
    // file is not, so its bases are compacted into `decompressed` instead.
    struct writable_buffer {
        char* data;
        size_t size;
    };
    auto const buffers = std::array{
        writable_buffer{result.decompressed_target, result.decompressed_size},
        writable_buffer{result.decompressed.data(), result.decompressed.size()},
        writable_buffer{result.sequence.data(), result.sequence.size()},
    };
    auto const writable = [&](char const* first, size_t size) {
        return std::any_of(buffers.begin(), buffers.end(), [&](writable_buffer const& buffer) {
            return buffer.data != nullptr && buffer.size >= size && first >= buffer.data &&
                   first + size <= buffer.data + buffer.size;
        });
    };
    size_t raw_total = 0;
    for (auto const& extent : result.extents) raw_total += static_cast<size_t>(extent.end - extent.begin);
    // Reserved up front so appending cannot move the buffer the extents are about to point at.
    std::string copied;
    copied.reserve(raw_total);
    std::vector<std::pair<size_t, std::pair<size_t, size_t>>> offsets;
    for (size_t index = 0; index < result.extents.size(); ++index) {
        auto const& extent = result.extents[index];
        auto const size = static_cast<size_t>(extent.end - extent.begin);
        if (writable(extent.begin, size)) {
            // Compaction only ever moves bytes towards the buffer's start.
            auto* write = const_cast<char*>(extent.begin);
            for (auto const* cursor = extent.begin; cursor != extent.end; ++cursor) {
                if (!fastx_is_sequence_whitespace(*cursor)) *write++ = *cursor;
            }
            result.extents[index] = {extent.begin, write};
        } else {
            auto const begin = copied.size();
            for (auto const* cursor = extent.begin; cursor != extent.end; ++cursor) {
                if (!fastx_is_sequence_whitespace(*cursor)) copied.push_back(*cursor);
            }
            offsets.emplace_back(index, std::pair{begin, copied.size()});
        }
    }
    if (!copied.empty()) {
        result.decompressed = std::move(copied);
        for (auto const& [index, span] : offsets) {
            result.extents[index] = {
                result.decompressed.data() + span.first, result.decompressed.data() + span.second
            };
        }
    }
}

inline Result<std::unique_ptr<fastx_sequence_file>>
load_fastx_sequence_file(std::string const& path, decompression_source source = {}) {
    auto file = fastx_mapped_file::load(path);
    if (!file) {
        return Err(Error::invalid_argument("cannot open FASTX file: " + path));
    }
    auto result = std::make_unique<fastx_sequence_file>();
    result->file = std::move(*file);
    auto data = result->file->data();
    auto& decompressed = result->decompressed;
    if (data.size() >= 2 && static_cast<unsigned char>(data[0]) == 0x1f &&
        static_cast<unsigned char>(data[1]) == 0x8b) {
        auto target = source.request(gzip_size_hint(data));
        bool insufficient = false;
        if (target.data != nullptr && target.capacity > 0) {
            auto written = gunzip_members_direct(data, target, insufficient, path);
            if (!written) return Err(written.error());
            if (!insufficient) {
                result->decompressed_target = target.data;
                result->decompressed_size = *written;
                result->storage_owner = std::move(target.owner);
                data = std::string_view{target.data, *written};
            }
        }
        if (result->decompressed_target == nullptr) {
            auto inflated = gunzip_members_into(data, decompressed, path);
            if (!inflated) return Err(inflated.error());
            data = decompressed;
        }
    }

    auto& sequence = result->sequence;
    auto& extents = result->extents;
    auto const first = data.find_first_not_of("\r\n");
    if (first != std::string_view::npos && data[first] == '@') {
        fastx_fastq_reader reader{data, path};
        std::vector<std::pair<size_t, size_t>> records;
        while (true) {
            auto const begin = sequence.size();
            auto next = reader.append_next_record(sequence);
            if (!next) return Err(Error::invalid_argument(next.error().message()));
            if (!*next) break;
            if (sequence.size() > begin) records.emplace_back(begin, sequence.size());
        }
        if (sequence.empty()) return result;
        for (auto const& [begin, end] : records) {
            extents.push_back({sequence.data() + begin, sequence.data() + end});
        }
    } else {
        extents = parallel_fastx_fasta_extents(data);
    }
    if (extents.empty()) {
        if (data.size() > 0) {
            return Err(Error::invalid_argument("FASTX parse error near: " + path));
        }
        return result;
    }
    compact_fastx_sequence_extents(*result);
    return result;
}

// Fixed worker pool loading FASTX files ahead of the GPU loop. A pthread spawn and join
// per genome costs tens of microseconds and dominates at high file counts. Workers pull
// ids in order while the main thread takes results in order, so at most depth loads are
// in flight and output order never depends on completion order. Loader exceptions are
// rethrown by take, matching std::async propagation into the build error handlers.
class fastx_load_pool {
   public:
    fastx_load_pool(
        std::span<std::filesystem::path const> paths,
        size_t depth,
        decompression_source source = {}
    )
        : paths_(paths),
          depth_(std::max(size_t{1}, depth)),
          source_(source),
          results_(paths.size()),
          errors_(paths.size()) {
        workers_.reserve(depth_);
        for (size_t i = 0; i < depth_; ++i) workers_.emplace_back([this] { work(); });
    }
    ~fastx_load_pool() {
        {
            std::lock_guard lock(mutex_);
            stop_ = true;
        }
        assign_.notify_all();
        for (auto& worker : workers_) worker.join();
    }
    fastx_load_pool(fastx_load_pool const&) = delete;
    fastx_load_pool& operator=(fastx_load_pool const&) = delete;

    [[nodiscard]] Result<std::unique_ptr<fastx_sequence_file>> take(size_t id) {
        std::unique_lock lock(mutex_);
        filled_.wait(lock, [&] { return results_[id].has_value() || errors_[id] != nullptr; });
        ++taken_;
        assign_.notify_all();
        lock.unlock();
        if (errors_[id] != nullptr) std::rethrow_exception(errors_[id]);
        return std::move(*results_[id]);
    }

   private:
    void work() {
        while (true) {
            size_t id;
            {
                std::unique_lock lock(mutex_);
                assign_.wait(lock, [&] {
                    return stop_ || next_ >= paths_.size() || next_ - taken_ < depth_;
                });
                if (stop_ || next_ >= paths_.size()) return;
                if (next_ - taken_ >= depth_) continue;
                id = next_++;
            }
            try {
                auto loaded = load_fastx_sequence_file(paths_[id].string(), source_);
                std::lock_guard lock(mutex_);
                results_[id] = std::move(loaded);
            } catch (...) {
                std::lock_guard lock(mutex_);
                errors_[id] = std::current_exception();
            }
            filled_.notify_all();
        }
    }
    std::span<std::filesystem::path const> paths_;
    size_t depth_;
    decompression_source source_;
    std::vector<std::optional<Result<std::unique_ptr<fastx_sequence_file>>>> results_;
    std::vector<std::exception_ptr> errors_;
    std::vector<std::thread> workers_;
    std::mutex mutex_;
    std::condition_variable assign_, filled_;
    size_t next_ = 0, taken_ = 0;
    bool stop_ = false;
};

}  // namespace cuddl::detail

namespace cuddl {

/// @brief Whether a build transfers decompressed bytes from page-locked memory by default.
///
/// Page-locked transfers win when the host writes to device-visible memory at full speed:
/// measured 2.1x over staging on an x86 host with a discrete GPU. On a coherent CPU/GPU system
/// the same mapping costs host writes more than the staging copy it removes, which is 2.9x
/// slower end to end on Grace Hopper. The architecture picks the default; `pinned` overrides it.
#if defined(__aarch64__)
inline constexpr bool default_pinned_transfer = false;
#else
inline constexpr bool default_pinned_transfer = true;
#endif

/// @brief How a build moved sequence bytes to the device.
///
/// A run that reports every byte as `direct` is reading the decompressed genome in place; a
/// large `staged` share means page-locked buffers were unavailable and bytes were copied into
/// staging on the consumer thread instead.
struct reference_build_statistics {
    size_t direct_bytes = 0;
    size_t staged_bytes = 0;
    size_t direct_chunks = 0;
    size_t staged_chunks = 0;
    size_t pinned_buffers = 0;
    size_t staging_bytes = 0;
    size_t batches = 0;
    size_t transfers = 0;  // runs copied in one piece, plus records split across pieces
};
}  // namespace cuddl::detail
