#pragma once

#include <libdeflate.h>

#include <algorithm>
#include <array>
#include <bit>
#include <condition_variable>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <format>
#include <fstream>
#include <memory>
#include <mutex>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <thread>
#include <utility>
#include <vector>

#include <cuddl/detail/dna.hpp>
#include <cuddl/error.hpp>

#if defined(__aarch64__) || defined(_M_ARM64)
    #include <arm_neon.h>
#endif
#if defined(__ARM_FEATURE_SVE)
    #include <arm_sve.h>
#elif defined(__x86_64__) || defined(_M_X64)
    #include <immintrin.h>
#endif

#if defined(__linux__)
    #include <fcntl.h>
    #include <sys/mman.h>
    #include <sys/stat.h>
    #include <unistd.h>
#endif

namespace cuddl::detail {

/// @brief A contiguous run of sequence bases (record headers and line breaks excluded).
struct fastx_sequence_extent {
    char const* begin;
    char const* end;
};

/// @brief One run of bases packed two bits each: its first word and its length in bases.
struct fastx_packed_record {
    uint64_t word;
    uint64_t bases;
};

/// @brief True for bytes that FASTA sequence consumers conventionally skip between bases.
[[nodiscard]] inline constexpr bool fastx_is_sequence_whitespace(char ch) noexcept {
    return ch == '\n' || ch == '\r' || ch == ' ' || ch == '\t';
}

// SIMD line scanners: https://github.com/tdortman/cuSBF
// Source revision: ec678b0750b0067d4fc66e066c8cd7a67cc5e792
/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
[[nodiscard]] inline size_t fastx_line_end_scalar(std::string_view data, size_t position) {
    while (position < data.size() && data[position] != '\n' && data[position] != '\r') {
        ++position;
    }
    return position;
}

#if (defined(__GNUC__) || defined(__clang__)) && defined(__x86_64__)
[[nodiscard]] __attribute__((target("avx2"))) inline size_t
fastx_line_end_avx2(std::string_view data, size_t position) {
    const __m256i newline = _mm256_set1_epi8('\n');
    const __m256i carriage_return = _mm256_set1_epi8('\r');
    while (data.size() - position >= 32) {
        const __m256i bytes =
            _mm256_loadu_si256(reinterpret_cast<const __m256i*>(data.data() + position));
        const auto mask = static_cast<uint32_t>(_mm256_movemask_epi8(_mm256_or_si256(
            _mm256_cmpeq_epi8(bytes, newline), _mm256_cmpeq_epi8(bytes, carriage_return)
        )));
        if (mask != 0) {
            return position + static_cast<size_t>(__builtin_ctz(mask));
        }
        position += 32;
    }
    return fastx_line_end_scalar(data, position);
}
#endif

#if (defined(__GNUC__) || defined(__clang__)) && defined(__x86_64__)
[[nodiscard]] __attribute__((target("avx512f,avx512bw"))) inline size_t
fastx_line_end_avx512(std::string_view data, size_t position) {
    while (data.size() - position >= 64) {
        auto const bytes = _mm512_loadu_si512(data.data() + position);
        auto const mask = _mm512_cmpeq_epi8_mask(bytes, _mm512_set1_epi8('\n')) |
                          _mm512_cmpeq_epi8_mask(bytes, _mm512_set1_epi8('\r'));
        if (mask != 0) return position + std::countr_zero(mask);
        position += 64;
    }
    return fastx_line_end_scalar(data, position);
}
#endif

#if defined(__ARM_FEATURE_SVE)
/// @brief SVE line-end scan; falls back to the scalar loop where SVE is unavailable.
[[nodiscard]] inline size_t fastx_line_end_sve(std::string_view data, size_t position) {
    while (position < data.size()) {
        const svbool_t active = svwhilelt_b8(position, data.size());
        const svuint8_t bytes =
            svld1_u8(active, reinterpret_cast<const uint8_t*>(data.data() + position));
        const svbool_t matches =
            svorr_b_z(active, svcmpeq_n_u8(active, bytes, '\n'), svcmpeq_n_u8(active, bytes, '\r'));
        if (svptest_any(active, matches)) {
            return position + svcntp_b8(active, svbrkb_z(active, matches));
        }
        position += svcntb();
    }
    return position;
}
#endif

#if defined(__aarch64__) || defined(_M_ARM64)
/// @brief NEON line-end scan over 16-byte blocks.
[[nodiscard]] inline size_t fastx_line_end_neon(std::string_view data, size_t position) {
    const uint8x16_t newline = vdupq_n_u8('\n');
    const uint8x16_t carriage_return = vdupq_n_u8('\r');
    while (data.size() - position >= 16) {
        const uint8x16_t bytes = vld1q_u8(reinterpret_cast<const uint8_t*>(data.data() + position));
        const uint8x16_t matches =
            vorrq_u8(vceqq_u8(bytes, newline), vceqq_u8(bytes, carriage_return));
        const uint64x2_t words = vreinterpretq_u64_u8(matches);
        const uint64_t low = vgetq_lane_u64(words, 0);
        if (low != 0) {
            return position + (std::countr_zero(low) >> 3);
        }
        const uint64_t high = vgetq_lane_u64(words, 1);
        if (high != 0) {
            return position + 8 + (std::countr_zero(high) >> 3);
        }
        position += 16;
    }
    return fastx_line_end_scalar(data, position);
}
#endif

using fastx_line_end_fn = decltype(&fastx_line_end_scalar);

/// @brief Selects the fastest line-end scanner the host supports.
[[nodiscard]] inline fastx_line_end_fn resolve_fastx_line_end() {
#if defined(__ARM_FEATURE_SVE)
    return fastx_line_end_sve;
#elif defined(__aarch64__) || defined(_M_ARM64)
    return fastx_line_end_neon;
#elif (defined(__GNUC__) || defined(__clang__)) && defined(__x86_64__)
    if (__builtin_cpu_supports("avx512bw")) return fastx_line_end_avx512;
    return __builtin_cpu_supports("avx2") ? fastx_line_end_avx2 : fastx_line_end_scalar;
#else
    return fastx_line_end_scalar;
#endif
}

static const fastx_line_end_fn line_end = resolve_fastx_line_end();

/// @brief First line-end position at or after @p position using the resolved scanner.
[[nodiscard]] inline size_t fastx_line_end(std::string_view data, size_t position) {
    return line_end(data, position);
}

/// @brief Read-only contiguous file payload for in-memory FASTX parsing.
///
/// On Linux a plain file is memory-mapped by default, so FASTA extents reference the mapping
/// with no copy, or read into memory it owns on request. Other platforms always read.
class fastx_mapped_file {
   public:
    fastx_mapped_file() = default;
    fastx_mapped_file(fastx_mapped_file const&) = delete;
    fastx_mapped_file& operator=(fastx_mapped_file const&) = delete;
    fastx_mapped_file(fastx_mapped_file&& other) noexcept {
        *this = std::move(other);
    }

    fastx_mapped_file& operator=(fastx_mapped_file&& other) noexcept {
        if (this != &other) {
            release();
            owned_storage_ = std::move(other.owned_storage_);
            data_ = other.data_;
            size_ = other.size_;
            other.data_ = nullptr;
            other.size_ = 0;
#if defined(__linux__)
            mapped_ = other.mapped_;
            mapped_size_ = other.mapped_size_;
            other.mapped_ = nullptr;
            other.mapped_size_ = 0;
#endif
        }
        return *this;
    }

    ~fastx_mapped_file() {
        release();
    }

    /**
     * @brief Maps or reads a file.
     *
     * Empty files succeed with empty data. Any failure carries the reason; the FASTX loader
     * maps it to its stable "cannot open" error.
     * @param read Read into owned memory instead of mapping. Unmapping write-locks the address
     *             space and shoots down TLBs on every core, which serialises a consumer that
     *             frees files loaded by dozens of threads; a single thread mapping ahead of
     *             others is better off mapping.
     */
    [[nodiscard]] static Result<std::unique_ptr<fastx_mapped_file>>
    load(std::string const& path, bool read = false) {
        auto buffer = std::make_unique<fastx_mapped_file>();
        auto loaded = buffer->load_from_path(path, read);
        if (!loaded) return Err(loaded.error());
        return buffer;
    }

    /// @brief Contiguous read-only file bytes.
    [[nodiscard]] std::string_view data() const noexcept {
        return std::string_view{data_, size_};
    }

    /// @brief True when the file is empty or load produced no bytes.
    [[nodiscard]] bool empty() const noexcept {
        return size_ == 0;
    }

   private:
    std::unique_ptr<char[]> owned_storage_;
    char const* data_{nullptr};
    size_t size_{0};

#if defined(__linux__)
    void* mapped_{nullptr};
    size_t mapped_size_{0};
#endif

    void release() {
#if defined(__linux__)
        if (mapped_ != nullptr) {
            munmap(mapped_, mapped_size_);
            mapped_ = nullptr;
            mapped_size_ = 0;
        }
#endif
        owned_storage_.reset();
        data_ = nullptr;
        size_ = 0;
    }

    [[nodiscard]] Result<void> load_from_path(std::string const& path, [[maybe_unused]] bool read) {
#if defined(__linux__)
        int const fd = ::open(path.c_str(), O_RDONLY);
        if (fd == -1) {
            return Err(Error::invalid_argument("Failed to open FASTA/FASTQ file: " + path));
        }

        struct stat file_status{};
        if (::fstat(fd, &file_status) != 0 || file_status.st_size < 0) {
            ::close(fd);
            return Err(Error::invalid_argument("Failed to stat FASTA/FASTQ file: " + path));
        }

        if (file_status.st_size == 0) {
            ::close(fd);
            return Ok();
        }

        auto const size = static_cast<size_t>(file_status.st_size);
        if (!read) {
            mapped_ = ::mmap(nullptr, size, PROT_READ, MAP_PRIVATE, fd, 0);
            ::close(fd);
            if (mapped_ == MAP_FAILED) {
                mapped_ = nullptr;
                return Err(Error::invalid_argument("Failed to mmap FASTA/FASTQ file: " + path));
            }
            mapped_size_ = size;
            data_ = static_cast<char const*>(mapped_);
            size_ = size;
            return Ok();
        }
        owned_storage_.reset(new char[size]);
        size_t done = 0;
        while (done < size) {
            auto const got =
                ::pread(fd, owned_storage_.get() + done, size - done, static_cast<off_t>(done));
            if (got <= 0) break;
            done += static_cast<size_t>(got);
        }
        ::close(fd);
        if (done != size) {
            owned_storage_.reset();
            return Err(Error::invalid_argument("Failed to read FASTA/FASTQ file: " + path));
        }
        data_ = owned_storage_.get();
        size_ = size;
        return Ok();
#else
        std::ifstream input(path, std::ios::binary);
        if (!input.is_open()) {
            return Err(Error::invalid_argument("Failed to open FASTA/FASTQ file: " + path));
        }
        input.seekg(0, std::ios::end);
        auto const file_size = input.tellg();
        if (file_size < 0) {
            return Err(Error::invalid_argument("Failed to size FASTA/FASTQ file: " + path));
        }
        owned_storage_.reset(new char[static_cast<size_t>(file_size)]);
        input.seekg(0, std::ios::beg);
        if (file_size > 0) {
            input.read(owned_storage_.get(), static_cast<std::streamsize>(file_size));
            if (!input) {
                return Err(Error::invalid_argument("Failed to read FASTA/FASTQ file: " + path));
            }
        }
        data_ = owned_storage_.get();
        size_ = static_cast<size_t>(file_size);
        return Ok();
#endif
    }
};

/// @brief Detected record format for a FASTX buffer.
enum class fastx_format : uint8_t {
    /// Format not yet determined from the first header.
    unknown,
    /// FASTA (`>` headers).
    fasta,
    /// FASTQ (`@` headers).
    fastq,
};

/**
 * @brief FASTQ parser over a contiguous in-memory buffer.
 *
 * Accumulates multiline sequence lines and validates multiline qualities against the
 * sequence length, exactly as the FASTA path's record scan excludes header bytes: only
 * sequence bytes reach the caller. The first header fixes the format; a later header of
 * the other kind is a mixed-format error.
 */
class fastx_fastq_reader {
   public:
    /**
     * @brief Constructs a reader over a contiguous in-memory FASTQ buffer.
     *
     * @param data         Entire file or decompressed payload.
     * @param source_name  Label used in parse error messages.
     */
    explicit fastx_fastq_reader(std::string_view data, std::string source_name = "<buffer>")
        : data_(data), source_name_(std::move(source_name)) {}

    /**
     * @brief Appends the next record's sequence bytes to @p sequence.
     *
     * @return @c false at end-of-buffer, @c true when a record was read, or an error.
     */
    [[nodiscard]] Result<bool> append_next_record(std::string& sequence) {
        auto header = CUDDL_TRY(read_header_line());
        if (header.empty()) {
            return false;
        }

        char const tag = header.front();
        if (format_ == fastx_format::unknown) {
            if (tag == '>') {
                format_ = fastx_format::fasta;
            } else if (tag == '@') {
                format_ = fastx_format::fastq;
            } else {
                return Err(parse_error("expected FASTA or FASTQ header"));
            }
        }

        char const expected = format_ == fastx_format::fasta ? '>' : '@';
        if (tag != expected) {
            return Err(parse_error("mixed FASTA and FASTQ records are not supported"));
        }
        if (format_ != fastx_format::fastq) {
            return Err(parse_error("mixed FASTA and FASTQ records are not supported"));
        }
        auto const base = sequence.size();
        CUDDL_TRY(read_fastq_sequence(sequence, base));
        return true;
    }

   private:
    std::string_view data_;
    std::string source_name_;
    size_t position_{0};
    fastx_format format_{fastx_format::unknown};
    uint64_t line_number_{};

    [[nodiscard]] Error parse_error(std::string_view message) const {
        return Error::invalid_argument(
            std::format("{}:{}: {}", source_name_, line_number_, message)
        );
    }

    [[nodiscard]] std::string_view read_line() {
        if (position_ >= data_.size()) {
            return {};
        }

        size_t const end = fastx_line_end(data_, position_);

        std::string_view const line = data_.substr(position_, end - position_);
        position_ = end;
        if (position_ < data_.size() && data_[position_] == '\r') {
            ++position_;
        }
        if (position_ < data_.size() && data_[position_] == '\n') {
            ++position_;
        }
        ++line_number_;
        return line;
    }

    [[nodiscard]] Result<std::string_view> read_header_line() {
        while (position_ < data_.size()) {
            std::string_view const line = read_line();
            if (!line.empty()) {
                return line;
            }
        }
        return std::string_view{};
    }

    [[nodiscard]] Result<void> read_fastq_sequence(std::string& sequence, size_t base) {
        while (position_ < data_.size()) {
            std::string_view const line = read_line();
            if (!line.empty() && line.front() == '+') {
                return read_fastq_qualities(sequence.size() - base);
            }
            sequence.append(line.data(), line.size());
        }
        return Err(parse_error("unterminated FASTQ record: missing '+' separator"));
    }

    [[nodiscard]] Result<void> read_fastq_qualities(uint64_t expected_length) {
        uint64_t quality_length = 0;
        while (quality_length < expected_length && position_ < data_.size()) {
            std::string_view const line = read_line();
            quality_length += line.size();
            if (quality_length > expected_length) {
                return Err(parse_error("FASTQ quality length exceeds sequence length"));
            }
        }
        if (quality_length != expected_length) {
            return Err(parse_error("FASTQ quality length does not match sequence length"));
        }
        return Ok();
    }
};

// Heap ownership keeps extent addresses stable, including short decompressed strings.
struct fastx_sequence_file {
    std::unique_ptr<fastx_mapped_file> file;
    std::string_view input;
    std::string decompressed;
    std::string sequence;
    std::vector<fastx_sequence_extent> extents;
    // Set when the caller supplied memory for the decompressed bytes, which then live outside
    // this object and stay valid as long as the caller keeps them. `decompressed` stays empty.
    char* decompressed_target = nullptr;
    size_t decompressed_size = 0;
    std::shared_ptr<void> storage_owner;
    // Set by pack_fastx_sequence_file, which consumes `extents`: runs of at least k bases as
    // two-bit words, sixteen bases each, every run starting on a word of its own.
    uint32_t const* words = nullptr;
    std::vector<fastx_packed_record> packed;
};

/// @brief Packs up to sixteen bases into a two-bit word, base @c j in bits @c 2j and @c 2j+1.
///
/// Codes are those of @ref encode_base. A byte that is not a base gets a meaningless code.
/// @return A mask with bit @c j set when byte @c j is not a base, or is past @p count.
[[nodiscard]] inline uint32_t pack_bases16_portable(char const* bases, size_t count, uint32_t& word) {
    if (count < 16) {
        uint32_t bad = 0;
        word = 0;
        for (uint32_t j = 0; j < 16; ++j) {
            auto const symbol = j < count ? encode_base(bases[j]) : uint8_t{0xFF};
            word |= static_cast<uint32_t>(symbol & 3U) << (2 * j);
            bad |= static_cast<uint32_t>(symbol == 0xFFU) << j;
        }
        return bad;
    }
    uint32_t bad = 0;
    word = 0;
    for (uint32_t half = 0; half < 2; ++half) {
        uint64_t x;
        std::memcpy(&x, bases + 8 * half, sizeof(x));
        constexpr uint64_t low7 = 0x7F7F7F7F7F7F7F7FULL;
        // High bit of each byte of v that is zero, without carries between bytes.
        auto const zero = [](uint64_t v) { return ~(((v & low7) + low7) | v | low7); };
        auto const upper = x & 0xDFDFDFDFDFDFDFDFULL;
        auto const valid = zero(upper ^ 0x4141414141414141ULL) |
                           zero(upper ^ 0x4343434343434343ULL) |
                           zero(upper ^ 0x4747474747474747ULL) | zero(upper ^ 0x5454545454545454ULL);
        auto codes = (x >> 1) & 0x0303030303030303ULL;
        codes = (codes | (codes >> 6)) & 0x000F000F000F000FULL;
        codes = (codes | (codes >> 12)) & 0x000000FF000000FFULL;
        codes = (codes | (codes >> 24)) & 0xFFFFULL;
        word |= static_cast<uint32_t>(codes) << (16 * half);
        // Byte j's flag lands on bit j.
        bad |= static_cast<uint32_t>(
                   ((~valid & 0x8080808080808080ULL) >> 7) * 0x0102040810204080ULL >> 56
               )
               << (8 * half);
    }
    return bad;
}

/// @brief Packs @p width bases from sixteen-base pieces, for a tail shorter than a full step.
inline uint64_t pack_bases_pieces(char const* bases, size_t count, uint32_t* words, size_t width) {
    uint64_t bad = 0;
    for (size_t piece = 0; piece < width / 16; ++piece) {
        auto const left = count > 16 * piece ? count - 16 * piece : 0;
        bad |= uint64_t{pack_bases16_portable(bases + 16 * piece, left, words[piece])} << (16 * piece);
    }
    return bad;
}

inline uint64_t pack_bases_portable(char const* bases, size_t count, uint32_t* words) {
    return pack_bases16_portable(bases, count, words[0]);
}

#if (defined(__x86_64__) || defined(__i386__)) && (defined(__GNUC__) || defined(__clang__))
/// @brief Packs 32 bases into two words: one compare per letter, multiply-adds for the codes.
__attribute__((target("avx2"))) inline uint64_t
pack_bases_avx2(char const* bases, size_t count, uint32_t* words) {
    if (count < 32) return pack_bases_pieces(bases, count, words, 32);
    auto const x = _mm256_loadu_si256(reinterpret_cast<__m256i const*>(bases));
    auto const upper = _mm256_and_si256(x, _mm256_set1_epi8(static_cast<char>(0xDF)));
    auto const valid = _mm256_or_si256(
        _mm256_or_si256(
            _mm256_cmpeq_epi8(upper, _mm256_set1_epi8('A')),
            _mm256_cmpeq_epi8(upper, _mm256_set1_epi8('C'))
        ),
        _mm256_or_si256(
            _mm256_cmpeq_epi8(upper, _mm256_set1_epi8('G')),
            _mm256_cmpeq_epi8(upper, _mm256_set1_epi8('T'))
        )
    );
    // Codes weighted 1, 4, 16, 64 and summed: every four bases make one byte.
    auto const codes = _mm256_and_si256(_mm256_srli_epi16(x, 1), _mm256_set1_epi8(3));
    auto const pairs = _mm256_maddubs_epi16(codes, _mm256_set1_epi16(0x0401));
    auto const quads = _mm256_madd_epi16(pairs, _mm256_set1_epi32(0x00100001));
    // Each lane's four bytes, then both lanes into one quadword.
    auto const gathered = _mm256_shuffle_epi8(
        quads, _mm256_setr_epi8(0, 4, 8, 12, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
                                0, 4, 8, 12, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1)
    );
    auto const both = _mm256_permutevar8x32_epi32(gathered, _mm256_setr_epi32(0, 4, 0, 0, 0, 0, 0, 0));
    _mm_storel_epi64(reinterpret_cast<__m128i*>(words), _mm256_castsi256_si128(both));
    return ~static_cast<uint64_t>(static_cast<uint32_t>(_mm256_movemask_epi8(valid))) &
           0xFFFFFFFFULL;
}

/// @brief Packs 64 bases into four words with byte-mask compares.
__attribute__((target("avx2,avx512f,avx512bw"))) inline uint64_t
pack_bases_avx512(char const* bases, size_t count, uint32_t* words) {
    if (count < 64) {
        // A short tail packs as two AVX2 halves.
        auto const low = pack_bases_avx2(bases, count, words);
        auto const high = pack_bases_avx2(bases + 32, count > 32 ? count - 32 : 0, words + 2);
        return low | (high << 32);
    }
    auto const x = _mm512_loadu_si512(bases);
    auto const upper = _mm512_and_si512(x, _mm512_set1_epi8(static_cast<char>(0xDF)));
    auto const valid = _mm512_cmpeq_epi8_mask(upper, _mm512_set1_epi8('A')) |
                       _mm512_cmpeq_epi8_mask(upper, _mm512_set1_epi8('C')) |
                       _mm512_cmpeq_epi8_mask(upper, _mm512_set1_epi8('G')) |
                       _mm512_cmpeq_epi8_mask(upper, _mm512_set1_epi8('T'));
    // Codes weighted 1, 4, 16, 64 and summed: every four bases make one byte.
    auto const codes = _mm512_and_si512(_mm512_srli_epi16(x, 1), _mm512_set1_epi8(3));
    auto const pairs = _mm512_maddubs_epi16(codes, _mm512_set1_epi16(0x0401));
    auto const quads = _mm512_madd_epi16(pairs, _mm512_set1_epi32(0x00100001));
    _mm_storeu_si128(reinterpret_cast<__m128i*>(words), _mm512_cvtepi32_epi8(quads));
    return ~static_cast<uint64_t>(valid);
}
#endif

#if defined(__aarch64__) || defined(_M_ARM64)
/// @brief Packs 64 bases into four words, sixteen bytes per vector.
///
/// The mask sets every bit from the first byte that is not a base on.
inline uint64_t pack_bases_neon(char const* bases, size_t count, uint32_t* words) {
    if (count < 64) return pack_bases_pieces(bases, count, words, 64);
    static constexpr int8_t shift_table[16] = {0, 2, 4, 6, 0, 2, 4, 6, 0, 2, 4, 6, 0, 2, 4, 6};
    auto const shifts = vld1q_s8(shift_table);
    for (size_t piece = 0; piece < 4; ++piece) {
        auto const x = vld1q_u8(reinterpret_cast<uint8_t const*>(bases) + 16 * piece);
        auto const upper = vandq_u8(x, vdupq_n_u8(0xDF));
        auto const valid = vorrq_u8(
            vorrq_u8(vceqq_u8(upper, vdupq_n_u8('A')), vceqq_u8(upper, vdupq_n_u8('C'))),
            vorrq_u8(vceqq_u8(upper, vdupq_n_u8('G')), vceqq_u8(upper, vdupq_n_u8('T')))
        );
        // One nibble per byte: set when the byte is not a base.
        auto const invalid = vget_lane_u64(
            vreinterpret_u64_u8(vshrn_n_u16(vreinterpretq_u16_u8(vmvnq_u8(valid)), 4)), 0
        );
        // Shift each code into its slot, then add four neighbours: their bits are disjoint.
        auto const codes = vshlq_u8(vandq_u8(vshrq_n_u8(x, 1), vdupq_n_u8(3)), shifts);
        auto const pairs = vpaddq_u8(codes, codes);
        words[piece] = vgetq_lane_u32(vreinterpretq_u32_u8(vpaddq_u8(pairs, pairs)), 0);
        if (invalid != 0) {
            return ~uint64_t{0} << (16 * piece + static_cast<size_t>(std::countr_zero(invalid)) / 4);
        }
    }
    return 0;
}
#endif

/// @brief A base packer and the bases it takes per step, a multiple of sixteen up to 64.
///
/// The packer returns a mask whose lowest set bit is the first byte that is not a base, or
/// the first byte past @c count; zero when all @c width bytes are bases.
struct bases_packer {
    uint64_t (*pack)(char const* bases, size_t count, uint32_t* words);
    size_t width;
};

/// @brief Selects the widest base packer the host supports.
[[nodiscard]] inline bases_packer resolve_bases_packer() {
#if (defined(__x86_64__) || defined(__i386__)) && (defined(__GNUC__) || defined(__clang__))
    if (__builtin_cpu_supports("avx512bw")) return {pack_bases_avx512, 64};
    if (__builtin_cpu_supports("avx2")) return {pack_bases_avx2, 32};
#endif
#if defined(__aarch64__) || defined(_M_ARM64)
    return {pack_bases_neon, 64};
#else
    return {pack_bases_portable, 16};
#endif
}

static const bases_packer packer = resolve_bases_packer();

/// @brief Packs a parsed file's records in place into two-bit words, run by run.
///
/// A record splits at every byte that is not a base, and runs shorter than @p k are dropped:
/// no k-mer holding such a byte is hashed, so the k-mers are those of the records. Output never
/// passes unread input: words are written only after the packer has read their bytes, a full
/// step writes a quarter of what it read, and a partial step writes only for a run of at least
/// @p k >= 16 bases, whose words take at most half of the bytes it read.
inline void pack_fastx_sequence_file(fastx_sequence_file& result, uint32_t k) {
    if (result.extents.empty() || k < 16) return;
    auto* const out = const_cast<char*>(result.extents.front().begin);
    uint64_t written = 0;
    for (auto const& extent : result.extents) {
        auto const* next = extent.begin;
        auto const* const end = extent.end;
        while (next < end) {
            while (next < end && encode_base(*next) == 0xFF) ++next;
            auto const* const start = next;
            auto const first = written;
            while (next < end) {
                uint32_t words[4];
                auto const bad = packer.pack(next, static_cast<size_t>(end - next), words);
                auto const bases =
                    bad == 0 ? packer.width : static_cast<size_t>(std::countr_zero(bad));
                // A partial step ends the run; a short run's partial words are never written.
                if (bases == packer.width || static_cast<size_t>(next + bases - start) >= k) {
                    auto const count = (bases + 15) / 16;
                    std::memcpy(out + written * sizeof(uint32_t), words, count * sizeof(uint32_t));
                    written += count;
                }
                next += bases;
                if (bases != packer.width) break;
            }
            auto const bases = static_cast<uint64_t>(next - start);
            if (bases >= k) {
                result.packed.push_back({first, bases});
            } else {
                written = first;
            }
        }
    }
    result.words = reinterpret_cast<uint32_t const*>(out);
    result.extents.clear();
}

/// @brief Host-visible buffer a caller offers for decompressed bytes.
///
/// Callers can reuse pageable or page-locked memory. `owner` keeps the storage alive for as
/// long as the parsed file holds it.
struct decompression_target {
    char* data = nullptr;
    size_t capacity = 0;
    std::shared_ptr<void> owner;
};

/// @brief Supplies storage for one file, or a null target when none is available.
///
/// Reusing buffers is the caller's problem, so it decides how much memory to
/// commit. A null target simply leaves the loader on its own growing buffer.
struct decompression_source {
    decompression_target (*acquire)(void* context, size_t bytes) = nullptr;
    void* context = nullptr;

    [[nodiscard]] decompression_target request(size_t bytes) const {
        return acquire != nullptr ? acquire(context, bytes) : decompression_target{};
    }
};

/// @brief libdeflate handle, one per thread because the object is single-threaded.
struct shared_gzip_decompressor {
    libdeflate_decompressor* handle{libdeflate_alloc_decompressor()};
    shared_gzip_decompressor() = default;
    shared_gzip_decompressor(shared_gzip_decompressor const&) = delete;
    shared_gzip_decompressor& operator=(shared_gzip_decompressor const&) = delete;
    ~shared_gzip_decompressor() {
        libdeflate_free_decompressor(handle);
    }
};

/// @brief Decodes one gzip member, checking structure and ISIZE but not checksums.
/// Skipping the payload CRC avoids a second pass over every decompressed byte.
[[nodiscard]] inline libdeflate_result decompress_gzip_member(
    libdeflate_decompressor* decoder,
    std::string_view input,
    char* output,
    size_t capacity,
    size_t& consumed,
    size_t& produced
) {
    auto const byte = [&](size_t i) {
        return static_cast<uint32_t>(static_cast<unsigned char>(input[i]));
    };
    if (input.size() < 18 || byte(0) != 0x1f || byte(1) != 0x8b || byte(2) != 8 ||
        (byte(3) & 0xe0) != 0) {
        return LIBDEFLATE_BAD_DATA;
    }
    auto const flags = byte(3);
    auto const end = input.size() - 8;
    size_t at = 10;
    if ((flags & 4) != 0) {
        if (end - at < 2) return LIBDEFLATE_BAD_DATA;
        auto const length = byte(at) | (byte(at + 1) << 8);
        at += 2;
        if (length > end - at) return LIBDEFLATE_BAD_DATA;
        at += length;
    }
    for (auto const flag : {8U, 16U}) {
        if ((flags & flag) != 0) {
            auto const terminator = input.find('\0', at);
            if (terminator == std::string_view::npos || terminator >= end) {
                return LIBDEFLATE_BAD_DATA;
            }
            at = terminator + 1;
        }
    }
    if ((flags & 2) != 0) {
        if (end - at < 2) return LIBDEFLATE_BAD_DATA;
        at += 2;
    }
    size_t deflate_bytes = 0;
    auto const status = libdeflate_deflate_decompress_ex(
        decoder, input.data() + at, end - at, output, capacity, &deflate_bytes, &produced
    );
    if (status != LIBDEFLATE_SUCCESS) return status;
    auto const trailer = at + deflate_bytes;
    auto const size = byte(trailer + 4) | (byte(trailer + 5) << 8) | (byte(trailer + 6) << 16) |
                      (byte(trailer + 7) << 24);
    if (static_cast<uint32_t>(produced) != size) return LIBDEFLATE_BAD_DATA;
    consumed = trailer + 8;
    return LIBDEFLATE_SUCCESS;
}

/// @brief Decompresses gzip members from a mapped buffer into @p output, appending.
///
/// Members are decompressed one at a time so concatenated streams (BGZF among them) work.
/// Each member's structure, DEFLATE data and length trailer are checked, but CRC32 is not.
/// `output` grows as needed, so pre-sizing storage saves reallocations without truncating data.
[[nodiscard]] inline Result<void>
gunzip_members_into(std::string_view input, std::string& output, std::string const& path) {
    static thread_local shared_gzip_decompressor shared;
    if (shared.handle == nullptr) {
        return Err(Error::resource("cannot allocate gzip decompressor"));
    }
    // Genomes compress around 3x; guessing low costs a realloc per member, not correctness.
    if (output.empty()) output.resize(std::max<size_t>(input.size() * 4, 1U << 16));
    size_t consumed = 0;
    size_t produced = 0;
    while (consumed < input.size()) {
        size_t member_in = 0;
        size_t member_out = 0;
        auto const status = decompress_gzip_member(
            shared.handle,
            input.substr(consumed),
            output.data() + produced,
            output.size() - produced,
            member_in,
            member_out
        );
        if (status == LIBDEFLATE_INSUFFICIENT_SPACE) {
            output.resize(output.size() * 2 + 1);
            continue;
        }
        if (status != LIBDEFLATE_SUCCESS) {
            return Err(Error::invalid_argument("gzip FASTX error: invalid stream: " + path));
        }
        consumed += member_in;
        produced += member_out;
    }
    output.resize(produced);
    return Ok();
}

/// @brief Decompresses gzip members straight into a caller's buffer.
///
/// Returns `Error::resource` when @p target is too small, which callers treat as a request to
/// fall back to the growing-string path rather than a failure.
[[nodiscard]] inline Result<size_t> gunzip_members_direct(
    std::string_view input,
    decompression_target target,
    bool& insufficient,
    std::string const& path
) {
    insufficient = false;
    static thread_local shared_gzip_decompressor shared;
    if (shared.handle == nullptr) {
        return Err(Error::resource("cannot allocate gzip decompressor"));
    }
    size_t consumed = 0;
    size_t produced = 0;
    while (consumed < input.size()) {
        size_t member_in = 0;
        size_t member_out = 0;
        auto const status = decompress_gzip_member(
            shared.handle,
            input.substr(consumed),
            target.data + produced,
            target.capacity - produced,
            member_in,
            member_out
        );
        if (status == LIBDEFLATE_INSUFFICIENT_SPACE) {
            // A caller-supplied buffer cannot grow, so the loader falls back instead.
            insufficient = true;
            return Result<size_t>::ok(0);
        }
        if (status != LIBDEFLATE_SUCCESS) {
            return Err(Error::invalid_argument("gzip FASTX error: invalid stream: " + path));
        }
        consumed += member_in;
        produced += member_out;
    }
    return produced;
}

/// @brief Uncompressed size the gzip trailer advertises, or 0 when it cannot be read.
///
/// `ISIZE` holds one member's length modulo 2^32, so a concatenated stream is only sized
/// correctly by its last member. A short buffer is refused later, never silently truncated.
/// @brief Exact decompressed size of @p path, or 0 when it is not a readable gzip file.
///
/// A gzip member ends with a little-endian ISIZE, so this needs a 4-byte read instead of a full
/// decompression pass. A corpus of these bounds how much a staged arena can ever hold.
[[nodiscard]] inline uint64_t gzip_decompressed_size(std::string const& path) {
    auto file = std::fopen(path.c_str(), "rb");
    if (file == nullptr) return 0;
    uint64_t size = 0;
    if (std::fseek(file, -4, SEEK_END) == 0) {
        unsigned char trailer[4] = {};
        if (std::fread(trailer, 1, sizeof(trailer), file) == sizeof(trailer)) {
            size = static_cast<uint64_t>(trailer[0]) | (static_cast<uint64_t>(trailer[1]) << 8) |
                   (static_cast<uint64_t>(trailer[2]) << 16) |
                   (static_cast<uint64_t>(trailer[3]) << 24);
        }
    }
    std::fclose(file);
    return size;
}

[[nodiscard]] inline size_t gzip_size_hint(std::string_view input) {
    if (input.size() < 8) return 0;
    auto const byte = [&](size_t index) {
        return static_cast<uint32_t>(static_cast<unsigned char>(input[index]));
    };
    auto const tail = input.size() - 4;
    return byte(tail) | (byte(tail + 1) << 8) | (byte(tail + 2) << 16) | (byte(tail + 3) << 24);
}

#if defined(__x86_64__) || defined(__i386__)
    #include <immintrin.h>
    #include <tmmintrin.h>
#elif defined(__ARM_NEON)
    #include <arm_neon.h>
#endif

namespace compact_impl {

/// @brief Shuffle controls per whitespace mask, for the vector paths.
///
/// Indexed by one half block's mask, an entry lists the positions of the bytes it keeps followed
/// by stop markers. Both the x86 shuffle and the aarch64 table lookup read the same table, and a
/// stop marker gathers nothing on either.
struct compact_shuffle_table {
    alignas(64) uint8_t control[256][16];
    uint8_t kept[256];
    compact_shuffle_table() noexcept {
        for (int mask = 0; mask < 256; ++mask) {
            int at = 0;
            for (int bit = 0; bit < 8; ++bit) {
                if ((mask & (1 << bit)) == 0) control[mask][at++] = static_cast<uint8_t>(bit);
            }
            for (; at < 16; ++at) control[mask][at] = 0x80U;
            kept[mask] = static_cast<uint8_t>(8 - __builtin_popcount(static_cast<unsigned>(mask)));
        }
    }
};

[[nodiscard]] inline compact_shuffle_table const& compact_shuffle() noexcept {
    static compact_shuffle_table const table;
    return table;
}

#if defined(__ARM_NEON)
/// @brief One bit per byte of @p flags, which holds a lane of 0x00 or 0xff per comparison.
[[nodiscard]] inline unsigned compact_mask(uint8x16_t flags) noexcept {
    constexpr std::uint8_t weights[16] = {1, 2, 4, 8, 16, 32, 64, 128, 1, 2, 4, 8, 16, 32, 64, 128};
    auto const weighted = vandq_u8(flags, vld1q_u8(weights));
    return static_cast<unsigned>(vaddv_u8(vget_low_u8(weighted))) |
           (static_cast<unsigned>(vaddv_u8(vget_high_u8(weighted))) << 8U);
}
#endif

}  // namespace compact_impl

#if defined(__ARM_NEON)
inline char* compact_block_neon(uint8x16_t block, uint8x16_t whitespace, char* out) {
    if (vmaxvq_u8(whitespace) == 0) {
        vst1q_u8(reinterpret_cast<uint8_t*>(out), block);
        return out + 16;
    }
    auto const& table = compact_impl::compact_shuffle();
    auto const flags = compact_impl::compact_mask(whitespace);
    auto const low = flags & 0xFFU;
    auto const high = (flags >> 8U) & 0xFFU;
    auto const packed_low = vqtbl1q_u8(block, vld1q_u8(table.control[low]));
    auto const packed_high = vqtbl1q_u8(vextq_u8(block, block, 8), vld1q_u8(table.control[high]));
    // Half-width stores cannot overwrite input beyond the loaded block when compacting in place.
    vst1_u8(reinterpret_cast<uint8_t*>(out), vget_low_u8(packed_low));
    out += table.kept[low];
    vst1_u8(reinterpret_cast<uint8_t*>(out), vget_low_u8(packed_high));
    return out + table.kept[high];
}

inline char* compact_sequence_whitespace_neon(char const* first, char const* last, char* out) {
    auto const newline = vdupq_n_u8('\n');
    auto const carriage = vdupq_n_u8('\r');
    auto const space = vdupq_n_u8(' ');
    auto const tab = vdupq_n_u8('\t');
    auto const* at = first;
    while (static_cast<size_t>(last - at) >= 16) {
        auto const block = vld1q_u8(reinterpret_cast<std::uint8_t const*>(at));
        auto const whitespace = vorrq_u8(
            vorrq_u8(vceqq_u8(block, newline), vceqq_u8(block, carriage)),
            vorrq_u8(vceqq_u8(block, space), vceqq_u8(block, tab))
        );
        out = compact_block_neon(block, whitespace, out);
        at += 16;
    }
    for (; at != last; ++at) {
        if (!fastx_is_sequence_whitespace(*at)) *out++ = *at;
    }
    return out;
}
#endif

#if defined(__x86_64__) || defined(__i386__)
/// @brief Writes the bytes of @p block whose @p flags bit is clear to @p out, two halves at a time.
///
/// Measured level with the sixteen byte path on a desktop whose store bandwidth saturates first,
/// and ahead of it where the machine has the width to spend.
__attribute__((target("avx2"))) inline char*
compact_block_avx2(__m256i block, unsigned flags, char* out) {
    auto const& table = compact_impl::compact_shuffle();
    auto const low_first = flags & 0xFFU;
    auto const low_second = (flags >> 8U) & 0xFFU;
    auto const high_first = (flags >> 16U) & 0xFFU;
    auto const high_second = (flags >> 24U) & 0xFFU;
    auto const control_first = _mm256_set_m128i(
        _mm_load_si128(reinterpret_cast<__m128i const*>(table.control[high_first])),
        _mm_load_si128(reinterpret_cast<__m128i const*>(table.control[low_first]))
    );
    auto const control_second = _mm256_set_m128i(
        _mm_load_si128(reinterpret_cast<__m128i const*>(table.control[high_second])),
        _mm_load_si128(reinterpret_cast<__m128i const*>(table.control[low_second]))
    );
    auto const packed_first = _mm256_shuffle_epi8(block, control_first);
    auto const packed_second = _mm256_shuffle_epi8(_mm256_bsrli_epi128(block, 8), control_second);
    // A lane holds the kept bytes of two halves, which are eight bytes apart in the vector and
    // adjacent in the output. The halves leave the vector in the order 0-7, 16-23, 8-15, 24-31,
    // and the output wants them in byte order, so each half is stored where its own count puts it.
    _mm_storel_epi64(reinterpret_cast<__m128i*>(out), _mm256_castsi256_si128(packed_first));
    out += table.kept[low_first];
    _mm_storel_epi64(reinterpret_cast<__m128i*>(out), _mm256_castsi256_si128(packed_second));
    out += table.kept[low_second];
    _mm_storel_epi64(reinterpret_cast<__m128i*>(out), _mm256_extracti128_si256(packed_first, 1));
    out += table.kept[high_first];
    _mm_storel_epi64(reinterpret_cast<__m128i*>(out), _mm256_extracti128_si256(packed_second, 1));
    out += table.kept[high_second];
    return out;
}

/// @brief The same compaction 32 bytes at a time.
__attribute__((target("avx2"))) inline char*
compact_sequence_whitespace_avx2(char const* first, char const* last, char* out) {
    auto const newline = _mm256_set1_epi8('\n');
    auto const carriage = _mm256_set1_epi8('\r');
    auto const space = _mm256_set1_epi8(' ');
    auto const tab = _mm256_set1_epi8('\t');
    auto const* at = first;
    while (static_cast<size_t>(last - at) >= 32) {
        auto const block = _mm256_loadu_si256(reinterpret_cast<__m256i const*>(at));
        auto const whitespace = _mm256_or_si256(
            _mm256_or_si256(_mm256_cmpeq_epi8(block, newline), _mm256_cmpeq_epi8(block, carriage)),
            _mm256_or_si256(_mm256_cmpeq_epi8(block, space), _mm256_cmpeq_epi8(block, tab))
        );
        out =
            compact_block_avx2(block, static_cast<unsigned>(_mm256_movemask_epi8(whitespace)), out);
        at += 32;
    }
    for (; at != last; ++at) {
        if (!fastx_is_sequence_whitespace(*at)) *out++ = *at;
    }
    return out;
}
#endif

#if (defined(__x86_64__) || defined(__i386__)) && (defined(__GNUC__) || defined(__clang__))
static bool const compact_avx512 =
    __builtin_cpu_supports("avx512bw") && __builtin_cpu_supports("avx512vbmi2");

__attribute__((target("avx512f,avx512bw,avx512vbmi2,popcnt"))) inline char*
compact_sequence_whitespace_avx512(char const* first, char const* last, char* out) {
    auto const* at = first;
    while (static_cast<size_t>(last - at) >= 64) {
        auto const block = _mm512_loadu_si512(at);
        auto const keep =
            ~(_mm512_cmpeq_epi8_mask(block, _mm512_set1_epi8('\n')) |
              _mm512_cmpeq_epi8_mask(block, _mm512_set1_epi8('\r')) |
              _mm512_cmpeq_epi8_mask(block, _mm512_set1_epi8(' ')) |
              _mm512_cmpeq_epi8_mask(block, _mm512_set1_epi8('\t')));
        _mm512_storeu_si512(out, _mm512_maskz_compress_epi8(keep, block));
        out += std::popcount(keep);
        at += 64;
    }
    for (; at != last; ++at) {
        if (!fastx_is_sequence_whitespace(*at)) *out++ = *at;
    }
    return out;
}
#endif

/// @brief Copies bases from [@p first, @p last) to @p out, dropping sequence whitespace.
///
/// A sequence line is a long run of bases closed by a line ending, so a test per byte is the bulk
/// of loading a corpus. Whole words are copied while none of their bytes is whitespace, and only a
/// word that holds one falls back to bytes, which leaves the common case at one store per eight
/// bases and keeps @p out no further along than the word being read.
///
/// @return The end of the written span.
inline char* compact_sequence_whitespace(char const* first, char const* last, char* out) {
    if (static_cast<size_t>(last - first) >= 64) {
#if defined(__ARM_NEON)
        return compact_sequence_whitespace_neon(first, last, out);
#elif defined(__x86_64__) || defined(__i386__)
        if (compact_avx512) return compact_sequence_whitespace_avx512(first, last, out);
        if (__builtin_cpu_supports("avx2")) {
            return compact_sequence_whitespace_avx2(first, last, out);
        }
#endif
    }
    constexpr uint64_t ones = 0x0101010101010101ULL;
    auto const has_zero_byte = [](uint64_t word) {
        return (word - ones) & ~word & 0x8080808080808080ULL;
    };
    auto const has_byte = [&](uint64_t word, uint64_t byte) {
        return has_zero_byte(word ^ (ones * byte));
    };
    auto const* word = first;
    while (static_cast<size_t>(last - word) >= sizeof(uint64_t)) {
        uint64_t value = 0;
        std::memcpy(&value, word, sizeof(value));
        auto const whitespace = has_byte(value, ' ') | has_byte(value, '\t') |
                                has_byte(value, '\n') | has_byte(value, '\r');
        if (whitespace == 0) {
            std::memcpy(out, word, sizeof(value));
            out += sizeof(value);
        } else {
            for (size_t index = 0; index < sizeof(value); ++index) {
                if (!fastx_is_sequence_whitespace(word[index])) *out++ = word[index];
            }
        }
        word += sizeof(value);
    }
    for (auto const* at = word; at != last; ++at) {
        if (!fastx_is_sequence_whitespace(*at)) *out++ = *at;
    }
    return out;
}

/// @brief First '>' in [@p first, @p last) that starts a line, or @p last.
///
/// The byte before @p first must be a line ending.
[[nodiscard]] inline char const* fasta_next_header(char const* first, char const* last) {
    for (auto const* at = first; at != last; ++at) {
        at = static_cast<char const*>(std::memchr(at, '>', static_cast<size_t>(last - at)));
        if (at == nullptr) return last;
        if (at == first || at[-1] == '\n' || at[-1] == '\r') return at;
    }
    return last;
}

#if defined(__x86_64__) || defined(__i386__)
/// @brief fasta_sequence_compact in one AVX2 pass: the header test rides on the whitespace test.
/// @brief @ref fasta_sequence_compact_avx2 on 64-byte blocks, compacting with vpcompressb.
///
/// A block's kept bytes are written as one full 64-byte store: @p out never passes the block
/// being read, so the store lands on bytes already loaded.
__attribute__((target("avx512f,avx512bw,avx512vbmi2,popcnt"))) inline char*
fasta_sequence_compact_avx512(char const* first, char const* last, char* out, char const*& stop) {
    auto const newline = _mm512_set1_epi8('\n');
    auto const carriage = _mm512_set1_epi8('\r');
    auto const space = _mm512_set1_epi8(' ');
    auto const tab = _mm512_set1_epi8('\t');
    auto const marker = _mm512_set1_epi8('>');
    // Bit set when the byte before the block ends a line; @p first follows a line ending.
    uint64_t carry = 1;
    auto const* at = first;
    while (static_cast<size_t>(last - at) >= 64) {
        auto const block = _mm512_loadu_si512(at);
        auto const ends =
            _mm512_cmpeq_epi8_mask(block, newline) | _mm512_cmpeq_epi8_mask(block, carriage);
        auto const headers = _mm512_cmpeq_epi8_mask(block, marker) & ((ends << 1U) | carry);
        if (headers != 0) {
            stop = at + std::countr_zero(headers);
            return compact_sequence_whitespace(at, stop, out);
        }
        carry = ends >> 63U;
        auto const keep =
            ~(ends | _mm512_cmpeq_epi8_mask(block, space) | _mm512_cmpeq_epi8_mask(block, tab));
        _mm512_storeu_si512(out, _mm512_maskz_compress_epi8(keep, block));
        out += std::popcount(keep);
        at += 64;
    }
    bool line_start = carry != 0;
    for (; at != last; ++at) {
        char const ch = *at;
        if (ch == '>' && line_start) break;
        line_start = ch == '\n' || ch == '\r';
        if (!fastx_is_sequence_whitespace(ch)) *out++ = ch;
    }
    stop = at;
    return out;
}

__attribute__((target("avx2"))) inline char*
fasta_sequence_compact_avx2(char const* first, char const* last, char* out, char const*& stop) {
    auto const newline = _mm256_set1_epi8('\n');
    auto const carriage = _mm256_set1_epi8('\r');
    auto const space = _mm256_set1_epi8(' ');
    auto const tab = _mm256_set1_epi8('\t');
    auto const marker = _mm256_set1_epi8('>');
    // Bit set when the byte before the block ends a line; @p first follows a line ending.
    unsigned carry = 1;
    auto const* at = first;
    while (static_cast<size_t>(last - at) >= 32) {
        auto const block = _mm256_loadu_si256(reinterpret_cast<__m256i const*>(at));
        auto const line_end =
            _mm256_or_si256(_mm256_cmpeq_epi8(block, newline), _mm256_cmpeq_epi8(block, carriage));
        auto const ends = static_cast<unsigned>(_mm256_movemask_epi8(line_end));
        auto const markers =
            static_cast<unsigned>(_mm256_movemask_epi8(_mm256_cmpeq_epi8(block, marker)));
        auto const headers = markers & ((ends << 1U) | carry);
        if (headers != 0) {
            stop = at + std::countr_zero(headers);
            return compact_sequence_whitespace(at, stop, out);
        }
        carry = ends >> 31U;
        auto const whitespace = _mm256_or_si256(
            line_end,
            _mm256_or_si256(_mm256_cmpeq_epi8(block, space), _mm256_cmpeq_epi8(block, tab))
        );
        out =
            compact_block_avx2(block, static_cast<unsigned>(_mm256_movemask_epi8(whitespace)), out);
        at += 32;
    }
    bool line_start = carry != 0;
    for (; at != last; ++at) {
        char const ch = *at;
        if (ch == '>' && line_start) break;
        line_start = ch == '\n' || ch == '\r';
        if (!fastx_is_sequence_whitespace(ch)) *out++ = ch;
    }
    stop = at;
    return out;
}
#endif

#if defined(__ARM_NEON)
inline char*
fasta_sequence_compact_neon(char const* first, char const* last, char* out, char const*& stop) {
    unsigned carry = 1;
    auto const* at = first;
    while (static_cast<size_t>(last - at) >= 16) {
        auto const block = vld1q_u8(reinterpret_cast<uint8_t const*>(at));
        auto const line_end =
            vorrq_u8(vceqq_u8(block, vdupq_n_u8('\n')), vceqq_u8(block, vdupq_n_u8('\r')));
        auto const ends = compact_impl::compact_mask(line_end);
        auto const markers = compact_impl::compact_mask(vceqq_u8(block, vdupq_n_u8('>')));
        auto const headers = markers & ((ends << 1U) | carry);
        if (headers != 0) {
            stop = at + std::countr_zero(headers);
            return compact_sequence_whitespace(at, stop, out);
        }
        carry = ends >> 15U;
        auto const whitespace = vorrq_u8(
            line_end, vorrq_u8(vceqq_u8(block, vdupq_n_u8(' ')), vceqq_u8(block, vdupq_n_u8('\t')))
        );
        out = compact_block_neon(block, whitespace, out);
        at += 16;
    }
    bool line_start = carry != 0;
    for (; at != last; ++at) {
        char const ch = *at;
        if (ch == '>' && line_start) break;
        line_start = ch == '\n' || ch == '\r';
        if (!fastx_is_sequence_whitespace(ch)) *out++ = ch;
    }
    stop = at;
    return out;
}
#endif

/// @brief Compacts one FASTA record's sequence from @p first to @p out, stopping at the next
/// header.
///
/// The byte before @p first must be a line ending, and @p out may alias @p first. @p stop receives
/// the next line-start '>' or @p last.
/// @return The end of the written span.
inline char*
fasta_sequence_compact(char const* first, char const* last, char* out, char const*& stop) {
#if (defined(__x86_64__) || defined(__i386__)) && (defined(__GNUC__) || defined(__clang__))
    if (compact_avx512) return fasta_sequence_compact_avx512(first, last, out, stop);
    if (__builtin_cpu_supports("avx2")) return fasta_sequence_compact_avx2(first, last, out, stop);
#endif
#if defined(__ARM_NEON)
    return fasta_sequence_compact_neon(first, last, out, stop);
#endif
    stop = fasta_next_header(first, last);
    return compact_sequence_whitespace(first, stop, out);
}

/// @brief Collects FASTA sequence extents with whitespace compacted out, in one pass over @p data.
///
/// An extent spans the bases between one line-start '>' header line and the next header (or the
/// end of @p data); bytes before the first header belong to no extent. Bases of consecutive
/// records are packed back to back from @p out, which may alias @p data.
[[nodiscard]] inline std::vector<fastx_sequence_extent>
fastx_fasta_compact_extents(std::string_view data, char* out) {
    std::vector<fastx_sequence_extent> extents;
    size_t header = data.find('>');
    while (header != std::string_view::npos && header != 0 && data[header - 1] != '\n' &&
           data[header - 1] != '\r') {
        header = data.find('>', header + 1);
    }
    if (header == std::string_view::npos) return extents;
    auto const* const last = data.data() + data.size();
    while (true) {
        auto const end = fastx_line_end(data, header);
        if (end + 1 >= data.size()) break;
        auto const* const sequence = data.data() + end + 1;
        char const* stop = nullptr;
        auto* const begin = out;
        out = fasta_sequence_compact(sequence, last, out, stop);
        if (stop != sequence) extents.push_back({begin, out});
        if (stop == last) break;
        header = static_cast<size_t>(stop - data.data());
    }
    return extents;
}

/// @brief Compacts sequence whitespace in place, leaving every extent a run of bases.
///
/// Consumers stage extents verbatim and choose piece boundaries on any base, which needs
/// contiguous bases. Compacting here moves the work onto the loader thread: each file is
/// compacted while the other loaders are still decompressing, and a consumer that used to skip
/// whitespace byte by byte now walks a dense span.
inline void compact_fastx_sequence_extents(fastx_sequence_file& result) {
    if (result.extents.empty()) return;
    // Extents point into whichever buffer holds the bytes: a page-locked target, the heap copy of
    // a compressed file, or the FASTQ sequence buffer. Those are writable; a memory-mapped plain
    // file is not, so its bases are compacted into `decompressed` instead.
    struct writable_buffer {
        char* data;
        size_t size;
    };
    auto const buffers = std::array{
        writable_buffer{result.decompressed_target, result.decompressed_size},
        writable_buffer{result.decompressed.data(), result.decompressed.size()},
        writable_buffer{result.sequence.data(), result.sequence.size()},
    };
    auto const writable = [&](char const* first, size_t size) {
        return std::any_of(buffers.begin(), buffers.end(), [&](writable_buffer const& buffer) {
            return buffer.data != nullptr && buffer.size >= size && first >= buffer.data &&
                   first + size <= buffer.data + buffer.size;
        });
    };
    size_t raw_total = 0;
    for (auto const& extent : result.extents)
        raw_total += static_cast<size_t>(extent.end - extent.begin);
    // Reserved up front so appending cannot move the buffer the extents are about to point at.
    std::string copied;
    copied.reserve(raw_total);
    std::vector<std::pair<size_t, std::pair<size_t, size_t>>> offsets;
    for (size_t index = 0; index < result.extents.size(); ++index) {
        auto const& extent = result.extents[index];
        auto const size = static_cast<size_t>(extent.end - extent.begin);
        if (writable(extent.begin, size)) {
            // Compaction only ever moves bytes towards the buffer's start.
            auto* const write = compact_sequence_whitespace(
                extent.begin, extent.end, const_cast<char*>(extent.begin)
            );
            result.extents[index] = {extent.begin, write};
        } else {
            auto const begin = copied.size();
            // Sized before the copy so the write needs no bounds check per byte.
            copied.resize(begin + size);
            auto* const write =
                compact_sequence_whitespace(extent.begin, extent.end, copied.data() + begin);
            copied.resize(static_cast<size_t>(write - copied.data()));
            offsets.emplace_back(index, std::pair{begin, copied.size()});
        }
    }
    if (!copied.empty()) {
        result.decompressed = std::move(copied);
        for (auto const& [index, span] : offsets) {
            result.extents[index] = {
                result.decompressed.data() + span.first, result.decompressed.data() + span.second
            };
        }
    }
}

inline Result<void>
parse_fastx_sequence_file(fastx_sequence_file& result, std::string const& path) {
    auto const data = std::exchange(result.input, {});
    auto& sequence = result.sequence;
    auto& extents = result.extents;
    auto const first = data.find_first_not_of("\r\n");
    if (first != std::string_view::npos && data[first] == '@') {
        fastx_fastq_reader reader{data, path};
        std::vector<std::pair<size_t, size_t>> records;
        while (true) {
            auto const begin = sequence.size();
            auto next = reader.append_next_record(sequence);
            if (!next) return Err(Error::invalid_argument(next.error().message()));
            if (!*next) break;
            if (sequence.size() > begin) records.emplace_back(begin, sequence.size());
        }
        if (sequence.empty()) return Ok();
        for (auto const& [begin, end] : records) {
            extents.push_back({sequence.data() + begin, sequence.data() + end});
        }
        compact_fastx_sequence_extents(result);
        return Ok();
    }
    // Mapped plain bytes are read-only; decompressed bytes can be compacted in place.
    char* out = result.decompressed_target;
    if (out == nullptr) {
        if (data.data() != result.decompressed.data()) result.decompressed.resize(data.size());
        out = result.decompressed.data();
    }
    extents = fastx_fasta_compact_extents(data, out);
    if (extents.empty() && !data.empty()) {
        return Err(Error::invalid_argument("FASTX parse error near: " + path));
    }
    return Ok();
}

/// @brief Compact and pack one cache-sized block at a time, without a genome-sized ASCII write.
/// Blocks end at line boundaries so header detection keeps its line-start invariant.
/// Carrying k - 1 compacted bytes preserves every window without duplicating one.
inline Result<void> pack_fasta_chunks(
    fastx_sequence_file& result,
    std::string_view data,
    char* out,
    uint32_t k,
    std::string const& path
) {
    size_t header = data.find('>');
    while (header != std::string_view::npos && header != 0 && data[header - 1] != '\n' &&
           data[header - 1] != '\r') {
        header = data.find('>', header + 1);
    }
    if (header == std::string_view::npos) {
        if (!data.empty()) return Err(Error::invalid_argument("FASTX parse error near: " + path));
        return Ok();
    }
    std::string scratch, carry;
    fastx_sequence_file chunk;
    uint64_t written = 0;
    bool has_sequence = false;
    auto const* const last = data.data() + data.size();
    while (true) {
        auto const end = fastx_line_end(data, header);
        if (end + 1 >= data.size()) break;
        auto const* at = data.data() + end + 1;
        carry.clear();
        while (at != last) {
            auto const offset = static_cast<size_t>(at - data.data());
            auto const boundary = offset + std::min<size_t>(16384, data.size() - offset);
            auto const limit = boundary == data.size()
                                   ? boundary
                                   : std::min(data.size(), fastx_line_end(data, boundary) + 1);
            auto const* const chunk_end = data.data() + limit;
            scratch.resize(carry.size() + static_cast<size_t>(chunk_end - at));
            std::memcpy(scratch.data(), carry.data(), carry.size());
            char const* stop = nullptr;
            auto* compact_end =
                fasta_sequence_compact(at, chunk_end, scratch.data() + carry.size(), stop);
            has_sequence |= stop != at;
            auto const bases = static_cast<size_t>(compact_end - scratch.data());
            carry.assign(compact_end - std::min<size_t>(k - 1, bases), compact_end);
            chunk.extents.push_back({scratch.data(), compact_end});
            pack_fastx_sequence_file(chunk, k);
            uint64_t words = 0;
            for (auto record : chunk.packed) {
                words = record.word + (record.bases + 15) / 16;
                record.word += written;
                result.packed.push_back(record);
            }
            std::memcpy(out + written * sizeof(uint32_t), scratch.data(), words * sizeof(uint32_t));
            written += words;
            chunk.packed.clear();
            at = stop;
            if (stop != chunk_end || stop == last) break;
        }
        if (at == last) break;
        header = static_cast<size_t>(at - data.data());
    }
    if (!has_sequence && !data.empty()) {
        return Err(Error::invalid_argument("FASTX parse error near: " + path));
    }
    result.words = reinterpret_cast<uint32_t const*>(out);
    result.input = {};
    return Ok();
}

inline Result<std::unique_ptr<fastx_sequence_file>> decode_fastx_sequence_file(
    std::unique_ptr<fastx_mapped_file> file,
    std::string const& path,
    decompression_source source,
    bool defer_fasta,
    uint32_t pack_k = 0
) {
    auto result = std::make_unique<fastx_sequence_file>();
    result->file = std::move(file);
    auto data = result->file->data();
    auto& decompressed = result->decompressed;
    if (data.size() >= 2 && static_cast<unsigned char>(data[0]) == 0x1f &&
        static_cast<unsigned char>(data[1]) == 0x8b) {
        // ISIZE is one member's length, so it sizes nothing for a BGZF stream: those end in an
        // empty EOF block, which reads back as zero, and a concatenated stream advertises only its
        // last member. Ask for the same over-estimate the heap path assumes, then grow the request
        // on a short target, which keeps a multi-member file off the heap path.
        auto request = std::max(gzip_size_hint(data), data.size() * 8);
        auto target = source.request(request);
        bool insufficient = false;
        bool inflated = false;
        size_t produced = 0;
        while (target.data != nullptr && target.capacity > 0) {
            auto const written = gunzip_members_direct(data, target, insufficient, path);
            if (!written) return Err(written.error());
            produced = *written;
            if (!insufficient) {
                inflated = true;
                break;
            }
            request = std::max(request * 2, data.size());
            target = source.request(request);
        }
        if (inflated) {
            result->decompressed_target = target.data;
            result->decompressed_size = produced;
            result->storage_owner = std::move(target.owner);
            data = std::string_view{target.data, produced};
        }
        if (result->decompressed_target == nullptr) {
            auto inflated = gunzip_members_into(data, decompressed, path);
            if (!inflated) return Err(inflated.error());
            data = decompressed;
        }
    }

    result->input = data;
    if (defer_fasta) {
        auto const first = data.find_first_not_of("\r\n");
        if (first != std::string_view::npos && data[first] == '>') {
            auto const end = fastx_line_end(data, first);
            // Empty first records and malformed inputs stay with the CPU parser.
            if (end + 1 < data.size() && data[end + 1] != '>') return result;
        }
    }
    if (pack_k >= 16) {
        auto const first = data.find_first_not_of("\r\n");
        if (first == std::string_view::npos || data[first] != '@') {
            char* out = result->decompressed_target;
            if (out == nullptr) {
                if (data.data() != result->decompressed.data())
                    result->decompressed.resize(data.size());
                out = result->decompressed.data();
            }
            CUDDL_TRY(pack_fasta_chunks(*result, data, out, pack_k, path));
            return result;
        }
    }
    CUDDL_TRY(parse_fastx_sequence_file(*result, path));
    return result;
}

inline Result<std::unique_ptr<fastx_sequence_file>> load_fastx_sequence_file(
    std::string const& path,
    decompression_source source = {},
    bool defer_fasta = false,
    bool read = false,
    uint32_t pack_k = 0
) {
    auto file = fastx_mapped_file::load(path, read);
    if (!file) return Err(Error::invalid_argument("cannot open FASTX file: " + path));
    return decode_fastx_sequence_file(std::move(*file), path, source, defer_fasta, pack_k);
}

// Fixed worker pool loading FASTX files ahead of the GPU loop. A pthread spawn and join
// per genome costs tens of microseconds and dominates at high file counts. Workers pull
// ids in order with a bounded number of outstanding loads. Consumers may collect by ID
// or by completion, retaining each input's ID. Loader exceptions are
// rethrown by take, matching std::async propagation into the build error handlers.
class fastx_load_pool {
   public:
    /// @param paths Files the pool loads in order.
    /// @param workers Loader threads.
    /// @param source Decompression buffer source; the default detects gzip by magic bytes.
    /// @param window  Files the loaders may hold ahead of the consumer, at least one per worker.
    ///                With ordered collection, the window hides a slow file: with a
    ///                window of one worker-worth there is no slack, and the consumer waits on the
    ///                straggler while the other loaders sit idle.
    /// @param defer_fasta Leave eligible FASTA bytes for a GPU normaliser.
    /// @param completion_order Collect through take_ready instead of take(id).
    /// @param pack_k Nonzero packs each loaded file into two-bit runs for k-mers this long.
    fastx_load_pool(
        std::span<std::filesystem::path const> paths,
        size_t workers,
        decompression_source source = {},
        size_t window = 0,
        bool defer_fasta = false,
        bool completion_order = false,
        uint32_t pack_k = 0
    )
        : paths_(paths),
          workers_(std::max(size_t{1}, workers)),
          window_(std::max({size_t{1}, window, workers_})),
          source_(source),
          defer_fasta_(defer_fasta),
          pack_k_(pack_k),
          results_(paths.size()),
          errors_(paths.size()),
          ready_(completion_order ? window_ : 0),
          retired_(defer_fasta ? window_ : 0),
          mapped_(defer_fasta ? window_ : 0) {
        threads_.reserve(workers_);
        if (defer_fasta_) {
            retirer_ = std::thread([this] { retire_files(); });
            mapper_ = std::thread([this] { map_files(); });
        }
        for (size_t i = 0; i < workers_; ++i) threads_.emplace_back([this] { work(); });
    }
    ~fastx_load_pool() {
        {
            std::lock_guard lock(mutex_);
            stop_ = true;
        }
        assign_.notify_all();
        mapped_ready_.notify_all();
        if (mapper_.joinable()) mapper_.join();
        for (auto& thread : threads_) thread.join();
        // Loaders may be waiting for retirement space, so stop the reaper only after joining them.
        if (retirer_.joinable()) {
            {
                std::lock_guard lock(retired_mutex_);
                retire_stop_ = true;
            }
            retired_ready_.notify_one();
            retirer_.join();
        }
    }
    fastx_load_pool(fastx_load_pool const&) = delete;
    fastx_load_pool& operator=(fastx_load_pool const&) = delete;

    [[nodiscard]] Result<std::unique_ptr<fastx_sequence_file>> take(size_t id) {
        std::unique_lock lock(mutex_);
        filled_.wait(lock, [&] { return results_[id].has_value() || errors_[id] != nullptr; });
        ++taken_;
        // One freed window slot needs one loader, not all of them: waking the rest is a syscall
        // and a context switch each, once per genome, at 100,000 genomes.
        assign_.notify_one();
        lock.unlock();
        if (errors_[id] != nullptr) std::rethrow_exception(errors_[id]);
        return std::move(*results_[id]);
    }

    [[nodiscard]] Result<std::pair<size_t, std::unique_ptr<fastx_sequence_file>>> take_ready() {
        if (ready_.empty())
            return Err(Error::invalid_argument("completion-order loading is disabled"));
        std::unique_lock lock(mutex_);
        filled_.wait(lock, [&] { return ready_count_ != 0; });
        auto const id = ready_[ready_head_];
        ready_head_ = (ready_head_ + 1) % ready_.size();
        --ready_count_;
        ++taken_;
        assign_.notify_one();
        lock.unlock();
        if (errors_[id] != nullptr) std::rethrow_exception(errors_[id]);
        return std::pair{id, CUDDL_TRY(std::move(*results_[id]))};
    }

    /// @brief @ref take_ready, or nothing once every id below the @ref cap limit is taken.
    [[nodiscard]] Result<std::optional<std::pair<size_t, std::unique_ptr<fastx_sequence_file>>>>
    take_ready_until_limit() {
        {
            std::unique_lock lock(mutex_);
            filled_.wait(lock, [&] { return ready_count_ != 0 || taken_ >= limit_; });
            if (ready_count_ == 0) return std::nullopt;
        }
        return CUDDL_TRY(take_ready());
    }

    /// @brief Completion-order results waiting to be taken.
    [[nodiscard]] size_t ready() {
        std::lock_guard lock(mutex_);
        return ready_count_;
    }

    /// @brief Stops the loaders before id @p limit, or after the ids they already claimed.
    ///
    /// A second consumer can own the ids past the returned limit without racing the loaders.
    /// @return How many ids the pool loads in total.
    size_t cap(size_t limit) {
        {
            std::lock_guard lock(mutex_);
            limit_ = std::clamp(limit, next_, limit_);
            limit = limit_;
        }
        assign_.notify_all();
        filled_.notify_all();
        return limit;
    }

   private:
    struct mapped_input {
        std::optional<Result<std::unique_ptr<fastx_mapped_file>>> file;
        std::exception_ptr error;
    };

    void map_files() {
        while (true) {
            size_t id;
            {
                std::unique_lock lock(mutex_);
                assign_.wait(lock, [&] {
                    return stop_ || mapped_next_ >= paths_.size() ||
                           mapped_next_ - taken_ < window_;
                });
                if (stop_ || mapped_next_ >= paths_.size()) return;
                id = mapped_next_;
            }
            mapped_input input;
            try {
                input.file = fastx_mapped_file::load(paths_[id].string());
            } catch (...) {
                input.error = std::current_exception();
            }
            {
                std::lock_guard lock(mutex_);
                mapped_[id % mapped_.size()] = std::move(input);
                ++mapped_next_;
            }
            mapped_ready_.notify_one();
        }
    }

    void retire(std::unique_ptr<fastx_mapped_file> file) {
        std::unique_lock lock(retired_mutex_);
        retired_space_.wait(lock, [&] { return retired_count_ < retired_.size(); });
        retired_[(retired_head_ + retired_count_) % retired_.size()] = std::move(file);
        ++retired_count_;
        lock.unlock();
        retired_ready_.notify_one();
    }

    void retire_files() {
        while (true) {
            std::unique_ptr<fastx_mapped_file> file;
            {
                std::unique_lock lock(retired_mutex_);
                retired_ready_.wait(lock, [&] { return retire_stop_ || retired_count_ != 0; });
                if (retired_count_ == 0) return;
                file = std::move(retired_[retired_head_]);
                retired_head_ = (retired_head_ + 1) % retired_.size();
                --retired_count_;
            }
            retired_space_.notify_one();
        }
    }

    void work() {
        while (true) {
            size_t id;
            mapped_input input;
            {
                std::unique_lock lock(mutex_);
                // The mapper owns the prefetch window; decoders wait for published mappings.
                if (defer_fasta_) {
                    mapped_ready_.wait(lock, [&] {
                        return stop_ || next_ >= paths_.size() || next_ < mapped_next_;
                    });
                } else {
                    assign_.wait(lock, [&] {
                        return stop_ || next_ >= limit_ || next_ - taken_ < window_;
                    });
                }
                if (stop_ || next_ >= limit_) return;
                id = next_++;
                if (defer_fasta_) input = std::move(mapped_[id % mapped_.size()]);
            }
            try {
                auto const path = paths_[id].string();
                auto loaded = [&]() -> Result<std::unique_ptr<fastx_sequence_file>> {
                    // Loaders free their files on the consumer, so they read rather than map.
                    if (!defer_fasta_)
                        return load_fastx_sequence_file(path, source_, false, true, pack_k_);
                    if (input.error) std::rethrow_exception(input.error);
                    if (!*input.file)
                        return Err(Error::invalid_argument("cannot open FASTX file: " + path));
                    return decode_fastx_sequence_file(std::move(**input.file), path, source_, true);
                }();
                if (pack_k_ != 0 && loaded) pack_fastx_sequence_file(**loaded, pack_k_);
                // Inflated or copied bytes no longer reference the file mapping.
                if (defer_fasta_ && loaded && (*loaded)->file &&
                    ((*loaded)->decompressed_target != nullptr ||
                     !(*loaded)->decompressed.empty())) {
                    retire(std::move((*loaded)->file));
                }
                std::lock_guard lock(mutex_);
                results_[id] = std::move(loaded);
                if (!ready_.empty()) {
                    ready_[(ready_head_ + ready_count_) % ready_.size()] = id;
                    ++ready_count_;
                }
            } catch (...) {
                std::lock_guard lock(mutex_);
                errors_[id] = std::current_exception();
                if (!ready_.empty()) {
                    ready_[(ready_head_ + ready_count_) % ready_.size()] = id;
                    ++ready_count_;
                }
            }
            filled_.notify_all();
        }
    }
    std::span<std::filesystem::path const> paths_;
    size_t workers_;
    size_t window_;
    decompression_source source_;
    bool defer_fasta_;
    uint32_t pack_k_;
    std::vector<std::optional<Result<std::unique_ptr<fastx_sequence_file>>>> results_;
    std::vector<std::exception_ptr> errors_;
    std::vector<size_t> ready_;
    std::vector<std::unique_ptr<fastx_mapped_file>> retired_;
    std::vector<mapped_input> mapped_;
    std::vector<std::thread> threads_;
    std::thread retirer_;
    std::thread mapper_;
    std::mutex mutex_;
    std::mutex retired_mutex_;
    std::condition_variable assign_, filled_;
    std::condition_variable retired_ready_, retired_space_;
    std::condition_variable mapped_ready_;
    size_t next_ = 0, taken_ = 0, limit_ = paths_.size();
    size_t ready_head_ = 0, ready_count_ = 0;
    size_t retired_head_ = 0, retired_count_ = 0;
    size_t mapped_next_ = 0;
    bool stop_ = false;
    bool retire_stop_ = false;
};

}  // namespace cuddl::detail

namespace cuddl {

/// @brief How a build moved sequence bytes to the device.
///
/// A run that reports every byte as `direct` is reading the decompressed genome in place; a
/// large `staged` share means page-locked buffers were unavailable and bytes were copied into
/// staging on the consumer thread instead.
struct reference_build_statistics {
    size_t direct_bytes = 0;
    size_t staged_bytes = 0;
    size_t direct_chunks = 0;
    size_t staged_chunks = 0;
    size_t pinned_buffers = 0;
    unsigned workers = 0;   // loaders the build ran, after its own defaulting
    bool in_place = false;  // the kernels read the loader's own buffers, so nothing was copied
    size_t staging_bytes = 0;
    size_t batches = 0;
    size_t transfers = 0;  // runs copied in one piece, plus records split across pieces
    /// Measure GPU row reset and sketch construction, excluding input transfers and readback.
    bool measure_resident = false;
    double resident_compute_ms = 0;
};
}  // namespace cuddl
