#pragma once

#include <zlib.h>
#include <algorithm>
#include <bit>
#include <cstdint>
#include <format>
#include <fstream>
#include <memory>
#include <string>
#include <string_view>
#include <thread>
#include <vector>

#include <cuddl/error.hpp>

#if defined(__aarch64__) || defined(_M_ARM64)
    #include <arm_neon.h>
#endif
#if defined(__ARM_FEATURE_SVE)
    #include <arm_sve.h>
#elif defined(__x86_64__) || defined(_M_X64)
    #include <immintrin.h>
#endif

#if defined(__linux__)
    #include <fcntl.h>
    #include <sys/mman.h>
    #include <sys/stat.h>
    #include <unistd.h>
#endif

namespace cuddl::detail {

/// @brief A contiguous run of sequence bytes (record header lines excluded).
struct fastx_sequence_extent {
    char const* begin;
    char const* end;
};

/// @brief True for bytes that FASTA sequence consumers conventionally skip between bases.
[[nodiscard]] inline constexpr bool fastx_is_sequence_whitespace(char ch) noexcept {
    return ch == '\n' || ch == '\r' || ch == ' ' || ch == '\t';
}

// SIMD line scanners: https://github.com/tdortman/cuSBF
// Source revision: ec678b0750b0067d4fc66e066c8cd7a67cc5e792
/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
[[nodiscard]] inline size_t fastx_line_end_scalar(std::string_view data, size_t position) {
    while (position < data.size() && data[position] != '\n' && data[position] != '\r') {
        ++position;
    }
    return position;
}

#if (defined(__GNUC__) || defined(__clang__)) && defined(__x86_64__) && !defined(__CUDACC__)
[[gnu::target("avx2")]] [[nodiscard]] inline size_t
fastx_line_end_avx2(std::string_view data, size_t position) {
    const __m256i newline = _mm256_set1_epi8('\n');
    const __m256i carriage_return = _mm256_set1_epi8('\r');
    while (data.size() - position >= 32) {
        const __m256i bytes =
            _mm256_loadu_si256(reinterpret_cast<const __m256i*>(data.data() + position));
        const auto mask = static_cast<uint32_t>(_mm256_movemask_epi8(_mm256_or_si256(
            _mm256_cmpeq_epi8(bytes, newline), _mm256_cmpeq_epi8(bytes, carriage_return)
        )));
        if (mask != 0) {
            return position + static_cast<size_t>(__builtin_ctz(mask));
        }
        position += 32;
    }
    return fastx_line_end_scalar(data, position);
}
#endif

#if defined(__ARM_FEATURE_SVE)
[[nodiscard]] inline size_t fastx_line_end_sve(std::string_view data, size_t position) {
    while (position < data.size()) {
        const svbool_t active = svwhilelt_b8(position, data.size());
        const svuint8_t bytes =
            svld1_u8(active, reinterpret_cast<const uint8_t*>(data.data() + position));
        const svbool_t matches =
            svorr_b_z(active, svcmpeq_n_u8(active, bytes, '\n'), svcmpeq_n_u8(active, bytes, '\r'));
        if (svptest_any(active, matches)) {
            return position + svcntp_b8(active, svbrkb_z(active, matches));
        }
        position += svcntb();
    }
    return position;
}
#endif

#if defined(__aarch64__) || defined(_M_ARM64)
[[nodiscard]] inline size_t fastx_line_end_neon(std::string_view data, size_t position) {
    const uint8x16_t newline = vdupq_n_u8('\n');
    const uint8x16_t carriage_return = vdupq_n_u8('\r');
    while (data.size() - position >= 16) {
        const uint8x16_t bytes = vld1q_u8(reinterpret_cast<const uint8_t*>(data.data() + position));
        const uint8x16_t matches =
            vorrq_u8(vceqq_u8(bytes, newline), vceqq_u8(bytes, carriage_return));
        const uint64x2_t words = vreinterpretq_u64_u8(matches);
        const uint64_t low = vgetq_lane_u64(words, 0);
        if (low != 0) {
            return position + (std::countr_zero(low) >> 3);
        }
        const uint64_t high = vgetq_lane_u64(words, 1);
        if (high != 0) {
            return position + 8 + (std::countr_zero(high) >> 3);
        }
        position += 16;
    }
    return fastx_line_end_scalar(data, position);
}
#endif

using fastx_line_end_fn = decltype(&fastx_line_end_scalar);

[[nodiscard]] inline fastx_line_end_fn resolve_fastx_line_end() {
#if defined(__ARM_FEATURE_SVE)
    return fastx_line_end_sve;
#elif defined(__aarch64__) || defined(_M_ARM64)
    return fastx_line_end_neon;
#elif (defined(__GNUC__) || defined(__clang__)) && defined(__x86_64__) && !defined(__CUDACC__)
    return __builtin_cpu_supports("avx2") ? fastx_line_end_avx2 : fastx_line_end_scalar;
#else
    return fastx_line_end_scalar;
#endif
}

static const fastx_line_end_fn line_end = resolve_fastx_line_end();

[[nodiscard]] inline size_t fastx_line_end(std::string_view data, size_t position) {
    return line_end(data, position);
}

/**
 * @brief Collects the sequence extents of every FASTA record in @p data.
 *
 * Each extent spans from the byte after a `>` header line to the byte before the next `>`
 * header line (or the end of the buffer), header bytes excluded. Search directly for header
 * markers with string_view::find; only header lines need a line-end scan. Bytes outside extents are
 * not part of any extent.
 */
[[nodiscard]] inline std::vector<fastx_sequence_extent> fastx_fasta_extents(std::string_view data) {
    std::vector<fastx_sequence_extent> extents;
    size_t sequence = std::string_view::npos;
    size_t header = data.find('>');
    while (header != std::string_view::npos) {
        if (header != 0 && data[header - 1] != '\n' && data[header - 1] != '\r') {
            header = data.find('>', header + 1);
            continue;
        }
        if (sequence != std::string_view::npos && header > sequence) {
            extents.push_back({data.data() + sequence, data.data() + header});
        }
        auto const end = fastx_line_end(data, header);
        sequence = end < data.size() ? end + 1 : data.size();
        header = data.find('>', sequence);
    }
    if (sequence != std::string_view::npos && sequence < data.size()) {
        extents.push_back({data.data() + sequence, data.data() + data.size()});
    }
    return extents;
}

// Collects every '>' offset in data[begin, end). Phase one of the parallel FASTA scan:
// pure search, no header interpretation.
inline void gather_header_candidates(
    std::string_view data,
    size_t begin,
    size_t end,
    std::vector<size_t>& out
) {
    auto const segment = data.substr(begin, end - begin);
    size_t pos = 0;
    while (true) {
        auto const found = segment.find('>', pos);
        if (found == std::string_view::npos) return;
        out.push_back(begin + found);
        pos = found + 1;
    }
}

// Serial header walk over ascending '>' candidates. Produces exactly
// fastx_fasta_extents(data): candidates before the cursor are bytes a
// serial search jumps over with its line-end skip, and the predecessor rule is local.
inline std::vector<fastx_sequence_extent>
walk_header_candidates(std::string_view data, std::vector<size_t> const& candidates) {
    std::vector<fastx_sequence_extent> extents;
    size_t sequence = std::string_view::npos;
    size_t cursor = 0;
    for (auto const header : candidates) {
        if (header < cursor) continue;
        if (header != 0 && data[header - 1] != '\n' && data[header - 1] != '\r') {
            cursor = header + 1;
            continue;
        }
        if (sequence != std::string_view::npos && header > sequence) {
            extents.push_back({data.data() + sequence, data.data() + header});
        }
        auto const end = fastx_line_end(data, header);
        sequence = end < data.size() ? end + 1 : data.size();
        cursor = sequence;
    }
    if (sequence != std::string_view::npos && sequence < data.size()) {
        extents.push_back({data.data() + sequence, data.data() + data.size()});
    }
    return extents;
}

// Parallel equivalent of fastx_fasta_extents for large inputs. Shards the
// '>' search (the full-buffer memchr pass) across threads, then walks the ordered
// candidates once. Small inputs use the serial scan directly.
inline std::vector<fastx_sequence_extent> parallel_fastx_fasta_extents(std::string_view data) {
    auto const hardware = std::max(1U, std::thread::hardware_concurrency());
    auto const shards =
        std::min<size_t>(std::min<unsigned>(hardware, 8U), data.size() / (size_t{64} << 20) + 1);
    if (shards <= 1) return fastx_fasta_extents(data);
    std::vector<std::vector<size_t>> gathered(shards);
    std::vector<std::thread> workers;
    workers.reserve(shards - 1);
    auto const span = (data.size() + shards - 1) / shards;
    for (size_t shard = 1; shard < shards; ++shard) {
        workers.emplace_back([&, shard] {
            auto const begin = std::min(shard * span, data.size());
            gather_header_candidates(
                data, begin, std::min(begin + span, data.size()), gathered[shard]
            );
        });
    }
    gather_header_candidates(data, 0, std::min(span, data.size()), gathered[0]);
    for (auto& worker : workers) worker.join();
    std::vector<size_t> candidates;
    for (auto const& shard : gathered)
        candidates.insert(candidates.end(), shard.begin(), shard.end());
    return walk_header_candidates(data, candidates);
}

/// @brief Read-only contiguous file payload for in-memory FASTX parsing.
///
/// Plain files stay memory-mapped on Linux, so FASTA extents reference the mapping with no
/// copy. Other platforms read the file into memory.
class fastx_mapped_file {
   public:
    fastx_mapped_file() = default;
    fastx_mapped_file(fastx_mapped_file const&) = delete;
    fastx_mapped_file& operator=(fastx_mapped_file const&) = delete;
    fastx_mapped_file(fastx_mapped_file&& other) noexcept {
        *this = std::move(other);
    }

    fastx_mapped_file& operator=(fastx_mapped_file&& other) noexcept {
        if (this != &other) {
            release();
            owned_storage_ = std::move(other.owned_storage_);
            data_ = other.data_;
            size_ = other.size_;
            other.data_ = nullptr;
            other.size_ = 0;
#if defined(__linux__)
            mapped_ = other.mapped_;
            mapped_size_ = other.mapped_size_;
            other.mapped_ = nullptr;
            other.mapped_size_ = 0;
#endif
        }
        return *this;
    }

    ~fastx_mapped_file() {
        release();
    }

    /**
     * @brief Loads a file via mmap (Linux) or read into memory.
     *
     * Empty files succeed with empty data. Any failure carries the reason; the FASTX loader
     * maps it to its stable "cannot open" error.
     */
    [[nodiscard]] static Result<std::unique_ptr<fastx_mapped_file>> load(std::string const& path) {
        auto buffer = std::make_unique<fastx_mapped_file>();
        auto loaded = buffer->load_from_path(path);
        if (!loaded) return Err(loaded.error());
        return buffer;
    }

    /// @brief Contiguous read-only file bytes.
    [[nodiscard]] std::string_view data() const noexcept {
        return std::string_view{data_, size_};
    }

    /// @brief True when the file is empty or load produced no bytes.
    [[nodiscard]] bool empty() const noexcept {
        return size_ == 0;
    }

   private:
    std::vector<char> owned_storage_;
    char const* data_{nullptr};
    size_t size_{0};

#if defined(__linux__)
    void* mapped_{nullptr};
    size_t mapped_size_{0};
#endif

    void release() {
#if defined(__linux__)
        if (mapped_ != nullptr) {
            munmap(mapped_, mapped_size_);
            mapped_ = nullptr;
            mapped_size_ = 0;
        }
#endif
        owned_storage_.clear();
        data_ = nullptr;
        size_ = 0;
    }

    [[nodiscard]] Result<void> load_from_path(std::string const& path) {
#if defined(__linux__)
        int const fd = ::open(path.c_str(), O_RDONLY);
        if (fd == -1) {
            return Err(Error::invalid_argument("Failed to open FASTA/FASTQ file: " + path));
        }

        struct stat file_status{};
        if (::fstat(fd, &file_status) != 0 || file_status.st_size < 0) {
            ::close(fd);
            return Err(Error::invalid_argument("Failed to stat FASTA/FASTQ file: " + path));
        }

        if (file_status.st_size == 0) {
            ::close(fd);
            return Ok();
        }

        mapped_size_ = static_cast<size_t>(file_status.st_size);
        mapped_ = ::mmap(nullptr, mapped_size_, PROT_READ, MAP_PRIVATE, fd, 0);
        ::close(fd);
        if (mapped_ == MAP_FAILED) {
            mapped_ = nullptr;
            mapped_size_ = 0;
            return Err(Error::invalid_argument("Failed to mmap FASTA/FASTQ file: " + path));
        }

        data_ = static_cast<char const*>(mapped_);
        size_ = mapped_size_;
        return Ok();
#else
        std::ifstream input(path, std::ios::binary);
        if (!input.is_open()) {
            return Err(Error::invalid_argument("Failed to open FASTA/FASTQ file: " + path));
        }
        input.seekg(0, std::ios::end);
        auto const file_size = input.tellg();
        if (file_size < 0) {
            return Err(Error::invalid_argument("Failed to size FASTA/FASTQ file: " + path));
        }
        owned_storage_.resize(static_cast<size_t>(file_size));
        input.seekg(0, std::ios::beg);
        if (!owned_storage_.empty()) {
            input.read(owned_storage_.data(), static_cast<std::streamsize>(owned_storage_.size()));
            if (!input) {
                return Err(Error::invalid_argument("Failed to read FASTA/FASTQ file: " + path));
            }
        }
        data_ = owned_storage_.data();
        size_ = owned_storage_.size();
        return Ok();
#endif
    }
};

/// @brief Detected record format for a FASTX buffer.
enum class fastx_format : uint8_t {
    /// Format not yet determined from the first header.
    unknown,
    /// FASTA (`>` headers).
    fasta,
    /// FASTQ (`@` headers).
    fastq,
};

/**
 * @brief FASTQ parser over a contiguous in-memory buffer.
 *
 * Accumulates multiline sequence lines and validates multiline qualities against the
 * sequence length, exactly as the FASTA path's record scan excludes header bytes: only
 * sequence bytes reach the caller. The first header fixes the format; a later header of
 * the other kind is a mixed-format error.
 */
class fastx_fastq_reader {
   public:
    /**
     * @brief Constructs a reader over a contiguous in-memory FASTQ buffer.
     *
     * @param data         Entire file or decompressed payload.
     * @param source_name  Label used in parse error messages.
     */
    explicit fastx_fastq_reader(std::string_view data, std::string source_name = "<buffer>")
        : data_(data), source_name_(std::move(source_name)) {}

    /**
     * @brief Appends the next record's sequence bytes to @p sequence.
     *
     * @return @c false at end-of-buffer, @c true when a record was read, or an error.
     */
    [[nodiscard]] Result<bool> append_next_record(std::string& sequence) {
        auto header = CUDDL_TRY(read_header_line());
        if (header.empty()) {
            return false;
        }

        char const tag = header.front();
        if (format_ == fastx_format::unknown) {
            if (tag == '>') {
                format_ = fastx_format::fasta;
            } else if (tag == '@') {
                format_ = fastx_format::fastq;
            } else {
                return Err(parse_error("expected FASTA or FASTQ header"));
            }
        }

        char const expected = format_ == fastx_format::fasta ? '>' : '@';
        if (tag != expected) {
            return Err(parse_error("mixed FASTA and FASTQ records are not supported"));
        }
        if (format_ != fastx_format::fastq) {
            return Err(parse_error("mixed FASTA and FASTQ records are not supported"));
        }
        auto const base = sequence.size();
        CUDDL_TRY(read_fastq_sequence(sequence, base));
        return true;
    }

   private:
    std::string_view data_;
    std::string source_name_;
    size_t position_{0};
    fastx_format format_{fastx_format::unknown};
    uint64_t line_number_{};

    [[nodiscard]] Error parse_error(std::string_view message) const {
        return Error::invalid_argument(
            std::format("{}:{}: {}", source_name_, line_number_, message)
        );
    }

    [[nodiscard]] std::string_view read_line() {
        if (position_ >= data_.size()) {
            return {};
        }

        size_t const end = fastx_line_end(data_, position_);

        std::string_view const line = data_.substr(position_, end - position_);
        position_ = end;
        if (position_ < data_.size() && data_[position_] == '\r') {
            ++position_;
        }
        if (position_ < data_.size() && data_[position_] == '\n') {
            ++position_;
        }
        ++line_number_;
        return line;
    }

    [[nodiscard]] Result<std::string_view> read_header_line() {
        while (position_ < data_.size()) {
            std::string_view const line = read_line();
            if (!line.empty()) {
                return line;
            }
        }
        return std::string_view{};
    }

    [[nodiscard]] Result<void> read_fastq_sequence(std::string& sequence, size_t base) {
        while (position_ < data_.size()) {
            std::string_view const line = read_line();
            if (!line.empty() && line.front() == '+') {
                return read_fastq_qualities(sequence.size() - base);
            }
            sequence.append(line.data(), line.size());
        }
        return Err(parse_error("unterminated FASTQ record: missing '+' separator"));
    }

    [[nodiscard]] Result<void> read_fastq_qualities(uint64_t expected_length) {
        uint64_t quality_length = 0;
        while (quality_length < expected_length && position_ < data_.size()) {
            std::string_view const line = read_line();
            quality_length += line.size();
            if (quality_length > expected_length) {
                return Err(parse_error("FASTQ quality length exceeds sequence length"));
            }
        }
        if (quality_length != expected_length) {
            return Err(parse_error("FASTQ quality length does not match sequence length"));
        }
        return Ok();
    }
};

// Heap ownership keeps extent addresses stable, including short decompressed strings.
struct fastx_sequence_file {
    std::unique_ptr<fastx_mapped_file> file;
    std::string decompressed;
    std::string sequence;
    std::vector<fastx_sequence_extent> extents;
};

inline Result<std::unique_ptr<fastx_sequence_file>> load_fastx_sequence_file(
    std::string const& path
) {
    auto file = fastx_mapped_file::load(path);
    if (!file) {
        return Err(Error::invalid_argument("cannot open FASTX file: " + path));
    }
    auto result = std::make_unique<fastx_sequence_file>();
    result->file = std::move(*file);
    auto data = result->file->data();
    auto& decompressed = result->decompressed;
    if (data.size() >= 2 && static_cast<unsigned char>(data[0]) == 0x1f &&
        static_cast<unsigned char>(data[1]) == 0x8b) {
        // zlib's gzread reports truncation as EOF. Check zlib errors here so
        // truncated or corrupt genomes cannot silently produce a partial database.
        std::unique_ptr<gzFile_s, decltype(&gzclose)> input{gzopen(path.c_str(), "rb"), &gzclose};
        if (!input) return Err(Error::resource("cannot open gzip FASTX file: " + path));
        char chunk[65536];
        while (true) {
            auto const size = gzread(input.get(), chunk, sizeof(chunk));
            int status{};
            auto const message = gzerror(input.get(), &status);
            if (size < 0 || (status != Z_OK && status != Z_STREAM_END)) {
                return Err(Error::invalid_argument("gzip FASTX error: " + std::string(message)));
            }
            if (size == 0) break;
            decompressed.append(chunk, static_cast<size_t>(size));
        }
        data = decompressed;
    }

    auto& sequence = result->sequence;
    auto& extents = result->extents;
    auto const first = data.find_first_not_of("\r\n");
    if (first != std::string_view::npos && data[first] == '@') {
        fastx_fastq_reader reader{data, path};
        std::vector<std::pair<size_t, size_t>> records;
        while (true) {
            auto const begin = sequence.size();
            auto next = reader.append_next_record(sequence);
            if (!next) return Err(Error::invalid_argument(next.error().message()));
            if (!*next) break;
            if (sequence.size() > begin) records.emplace_back(begin, sequence.size());
        }
        if (sequence.empty()) return result;
        for (auto const& [begin, end] : records) {
            extents.push_back({sequence.data() + begin, sequence.data() + end});
        }
    } else {
        extents = parallel_fastx_fasta_extents(data);
    }
    if (extents.empty()) {
        if (data.size() > 0) {
            return Err(Error::invalid_argument("FASTX parse error near: " + path));
        }
        return result;
    }

    return result;
}

}  // namespace cuddl::detail
