[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "subprojects/packagefiles/rust/vendor"

[source."git+https://github.com/bluenote-1577/partitions.git"]
git = "https://github.com/bluenote-1577/partitions.git"
replace-with = "vendored-sources"
